// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_3_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        in1_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID,
        in1_V_TDATA,
        in1_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   in1_V_TVALID;
input   out0_V_TREADY;
input  [15:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out0_V_TDATA;
output   out0_V_TVALID;
input  [15:0] in1_V_TDATA;
output   in1_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out0_V_TVALID;
reg in1_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln249_fu_247_p2;
wire   [0:0] icmp_ln253_fu_259_p2;
reg    ap_predicate_op55_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_1007;
reg   [0:0] icmp_ln249_reg_1007_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_1024;
reg   [0:0] icmp_ln290_reg_1024_pp0_iter1_reg;
reg    ap_predicate_op173_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] threshs_address0;
reg    threshs_ce0;
wire   [6:0] threshs_q0;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
reg    in1_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_1002;
wire   [3:0] trunc_ln257_fu_352_p1;
wire   [7:0] add_ln840_9_fu_815_p2;
reg   [7:0] add_ln840_9_reg_1019;
reg   [7:0] add_ln840_9_reg_1019_pp0_iter1_reg;
wire   [0:0] icmp_ln290_fu_827_p2;
reg   [9:0] ap_phi_mux_inElem_1_phi_fu_195_p26;
wire   [9:0] inElem_fu_336_p1;
wire   [9:0] ap_phi_reg_pp0_iter0_inElem_1_reg_192;
wire   [9:0] tmp_fu_305_p14;
wire   [63:0] idxprom2_i_fu_878_p1;
reg   [31:0] sf_fu_96;
wire   [31:0] sf_2_fu_821_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [9:0] i_fu_100;
wire   [9:0] i_2_fu_253_p2;
reg   [9:0] ap_sig_allocacmp_i_1;
reg   [7:0] add_i_i_i3_960_fu_104;
reg   [9:0] inputBuf_V_fu_108;
reg   [9:0] inputBuf_V_1_fu_112;
reg   [9:0] inputBuf_V_2_fu_116;
reg   [9:0] inputBuf_V_3_fu_120;
reg   [9:0] inputBuf_V_4_fu_124;
reg   [9:0] inputBuf_V_5_fu_128;
reg   [9:0] inputBuf_V_6_fu_132;
reg   [9:0] inputBuf_V_7_fu_136;
reg   [9:0] inputBuf_V_8_fu_140;
reg   [9:0] inputBuf_V_9_fu_144;
reg   [9:0] inputBuf_V_10_fu_148;
reg   [9:0] inputBuf_V_11_fu_152;
reg   [31:0] nf_1_fu_156;
wire   [31:0] nf_3_fu_850_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [3:0] tmp_fu_305_p13;
wire   [0:0] icmp_ln272_fu_423_p2;
wire   [0:0] local_temp_V_fu_437_p1;
wire   [0:0] xor_ln1019_fu_513_p2;
wire   [0:0] p_Result_s_fu_419_p1;
wire   [0:0] xor_ln1019_1_fu_519_p2;
wire   [0:0] local_temp_V_1_fu_441_p3;
wire   [0:0] xor_ln1019_2_fu_537_p2;
wire   [0:0] p_Result_1_fu_529_p3;
wire   [0:0] xor_ln1019_3_fu_543_p2;
wire   [0:0] local_temp_V_2_fu_449_p3;
wire   [0:0] xor_ln1019_4_fu_561_p2;
wire   [0:0] p_Result_2_fu_553_p3;
wire   [0:0] xor_ln1019_5_fu_567_p2;
wire   [0:0] p_Result_3_fu_577_p3;
wire   [0:0] local_temp_V_3_fu_457_p3;
wire   [0:0] xor_ln1019_6_fu_585_p2;
wire   [0:0] xor_ln1019_7_fu_591_p2;
wire   [0:0] local_temp_V_4_fu_465_p3;
wire   [0:0] xor_ln1019_8_fu_609_p2;
wire   [0:0] p_Result_4_fu_601_p3;
wire   [0:0] xor_ln1019_9_fu_615_p2;
wire   [0:0] p_Result_5_fu_625_p3;
wire   [0:0] local_temp_V_5_fu_473_p3;
wire   [0:0] xor_ln1019_10_fu_633_p2;
wire   [0:0] xor_ln1019_11_fu_639_p2;
wire   [0:0] p_Result_6_fu_649_p3;
wire   [0:0] local_temp_V_6_fu_481_p3;
wire   [0:0] xor_ln1019_12_fu_657_p2;
wire   [0:0] xor_ln1019_13_fu_663_p2;
wire   [0:0] p_Result_7_fu_673_p3;
wire   [0:0] local_temp_V_7_fu_489_p3;
wire   [0:0] xor_ln1019_14_fu_681_p2;
wire   [0:0] xor_ln1019_15_fu_687_p2;
wire   [0:0] p_Result_8_fu_697_p3;
wire   [0:0] local_temp_V_8_fu_497_p3;
wire   [0:0] xor_ln1019_16_fu_705_p2;
wire   [0:0] xor_ln1019_17_fu_711_p2;
wire   [0:0] local_temp_V_9_fu_505_p3;
wire   [0:0] xor_ln1019_18_fu_729_p2;
wire   [0:0] p_Result_9_fu_721_p3;
wire   [0:0] xor_ln1019_19_fu_735_p2;
wire   [7:0] select_ln272_fu_429_p3;
wire   [7:0] zext_ln840_fu_693_p1;
wire   [1:0] zext_ln780_6_fu_669_p1;
wire   [1:0] zext_ln780_5_fu_645_p1;
wire   [1:0] add_ln840_1_fu_751_p2;
wire   [1:0] zext_ln780_7_fu_717_p1;
wire   [1:0] add_ln840_2_fu_757_p2;
wire   [7:0] zext_ln840_2_fu_763_p1;
wire   [7:0] add_ln840_fu_745_p2;
wire   [1:0] zext_ln780_4_fu_621_p1;
wire   [1:0] zext_ln780_1_fu_549_p1;
wire   [1:0] add_ln840_4_fu_773_p2;
wire   [1:0] zext_ln780_fu_525_p1;
wire   [1:0] add_ln840_5_fu_779_p2;
wire   [1:0] zext_ln780_2_fu_573_p1;
wire   [1:0] zext_ln840_1_fu_741_p1;
wire   [1:0] add_ln840_6_fu_789_p2;
wire   [1:0] zext_ln780_3_fu_597_p1;
wire   [1:0] add_ln840_7_fu_795_p2;
wire   [2:0] zext_ln840_4_fu_801_p1;
wire   [2:0] zext_ln840_3_fu_785_p1;
wire   [2:0] add_ln840_8_fu_805_p2;
wire   [7:0] zext_ln840_5_fu_811_p1;
wire   [7:0] add_ln840_3_fu_767_p2;
wire   [31:0] nf_fu_838_p2;
wire   [0:0] icmp_ln302_fu_844_p2;
wire   [7:0] zext_ln1039_fu_882_p1;
wire   [0:0] icmp_ln1039_fu_886_p2;
wire   [0:0] result_V_fu_891_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
reg    ap_condition_718;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_3_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
threshs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_address0),
    .ce0(threshs_ce0),
    .q0(threshs_q0)
);

MVAU_hls_3_mux_124_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 10 ),
    .din11_WIDTH( 10 ),
    .din12_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
mux_124_10_1_1_U1(
    .din0(inputBuf_V_fu_108),
    .din1(inputBuf_V_1_fu_112),
    .din2(inputBuf_V_2_fu_116),
    .din3(inputBuf_V_3_fu_120),
    .din4(inputBuf_V_4_fu_124),
    .din5(inputBuf_V_5_fu_128),
    .din6(inputBuf_V_6_fu_132),
    .din7(inputBuf_V_7_fu_136),
    .din8(inputBuf_V_8_fu_140),
    .din9(inputBuf_V_9_fu_144),
    .din10(inputBuf_V_10_fu_148),
    .din11(inputBuf_V_11_fu_152),
    .din12(tmp_fu_305_p13),
    .dout(tmp_fu_305_p14)
);

MVAU_hls_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_718)) begin
        if ((icmp_ln249_fu_247_p2 == 1'd0)) begin
            i_fu_100 <= i_2_fu_253_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_100 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_718)) begin
        if (((icmp_ln249_fu_247_p2 == 1'd0) & (icmp_ln290_fu_827_p2 == 1'd1))) begin
            nf_1_fu_156 <= nf_3_fu_850_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_156 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_718)) begin
        if (((icmp_ln249_fu_247_p2 == 1'd0) & (icmp_ln290_fu_827_p2 == 1'd1))) begin
            sf_fu_96 <= 32'd0;
        end else if (((icmp_ln249_fu_247_p2 == 1'd0) & (icmp_ln290_fu_827_p2 == 1'd0))) begin
            sf_fu_96 <= sf_2_fu_821_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_96 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_i_i_i3_960_fu_104 <= add_ln840_9_fu_815_p2;
        add_ln840_9_reg_1019 <= add_ln840_9_fu_815_p2;
        icmp_ln290_reg_1024 <= icmp_ln290_fu_827_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_ln840_9_reg_1019_pp0_iter1_reg <= add_ln840_9_reg_1019;
        icmp_ln249_reg_1007_pp0_iter1_reg <= icmp_ln249_reg_1007;
        icmp_ln290_reg_1024_pp0_iter1_reg <= icmp_ln290_reg_1024;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_1007 <= icmp_ln249_fu_247_p2;
        nf_2_reg_1002 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd10))) begin
        inputBuf_V_10_fu_148 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln257_fu_352_p1 == 4'd10) & ~(trunc_ln257_fu_352_p1 == 4'd0) & ~(trunc_ln257_fu_352_p1 == 4'd1) & ~(trunc_ln257_fu_352_p1 == 4'd2) & ~(trunc_ln257_fu_352_p1 == 4'd3) & ~(trunc_ln257_fu_352_p1 == 4'd4) & ~(trunc_ln257_fu_352_p1 == 4'd5) & ~(trunc_ln257_fu_352_p1 == 4'd6) & ~(trunc_ln257_fu_352_p1 == 4'd7) & ~(trunc_ln257_fu_352_p1 == 4'd8) & ~(trunc_ln257_fu_352_p1 == 4'd9) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        inputBuf_V_11_fu_152 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd1))) begin
        inputBuf_V_1_fu_112 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd2))) begin
        inputBuf_V_2_fu_116 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd3))) begin
        inputBuf_V_3_fu_120 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd4))) begin
        inputBuf_V_4_fu_124 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd5))) begin
        inputBuf_V_5_fu_128 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd6))) begin
        inputBuf_V_6_fu_132 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd7))) begin
        inputBuf_V_7_fu_136 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd8))) begin
        inputBuf_V_8_fu_140 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd9))) begin
        inputBuf_V_9_fu_144 <= inElem_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_352_p1 == 4'd0))) begin
        inputBuf_V_fu_108 <= inElem_fu_336_p1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_247_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_259_p2 == 1'd0) & (icmp_ln249_fu_247_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_195_p26 = tmp_fu_305_p14;
    end else if ((((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd10)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd0)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd1)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd2)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd3)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd4)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd5)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd6)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd7)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd8)) | ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0) & (trunc_ln257_fu_352_p1 == 4'd9)) | (~(trunc_ln257_fu_352_p1 == 4'd10) & ~(trunc_ln257_fu_352_p1 == 4'd0) & ~(trunc_ln257_fu_352_p1 == 4'd1) & ~(trunc_ln257_fu_352_p1 == 4'd2) & ~(trunc_ln257_fu_352_p1 == 4'd3) & ~(trunc_ln257_fu_352_p1 == 4'd4) & ~(trunc_ln257_fu_352_p1 == 4'd5) & ~(trunc_ln257_fu_352_p1 == 4'd6) & ~(trunc_ln257_fu_352_p1 == 4'd7) & ~(trunc_ln257_fu_352_p1 == 4'd8) & ~(trunc_ln257_fu_352_p1 == 4'd9) & (icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0)))) begin
        ap_phi_mux_inElem_1_phi_fu_195_p26 = inElem_fu_336_p1;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_195_p26 = ap_phi_reg_pp0_iter0_inElem_1_reg_192;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_100;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_156;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_96;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op55_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op55_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TDATA_blk_n = in1_V_TVALID;
    end else begin
        in1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_247_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in1_V_TREADY = 1'b1;
    end else begin
        in1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op173_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (ap_predicate_op173_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out0_V_TVALID = 1'b1;
    end else begin
        out0_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        threshs_ce0 = 1'b1;
    end else begin
        threshs_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (icmp_ln249_reg_1007_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln840_1_fu_751_p2 = (zext_ln780_6_fu_669_p1 + zext_ln780_5_fu_645_p1);

assign add_ln840_2_fu_757_p2 = (add_ln840_1_fu_751_p2 + zext_ln780_7_fu_717_p1);

assign add_ln840_3_fu_767_p2 = (zext_ln840_2_fu_763_p1 + add_ln840_fu_745_p2);

assign add_ln840_4_fu_773_p2 = (zext_ln780_4_fu_621_p1 + zext_ln780_1_fu_549_p1);

assign add_ln840_5_fu_779_p2 = (add_ln840_4_fu_773_p2 + zext_ln780_fu_525_p1);

assign add_ln840_6_fu_789_p2 = (zext_ln780_2_fu_573_p1 + zext_ln840_1_fu_741_p1);

assign add_ln840_7_fu_795_p2 = (add_ln840_6_fu_789_p2 + zext_ln780_3_fu_597_p1);

assign add_ln840_8_fu_805_p2 = (zext_ln840_4_fu_801_p1 + zext_ln840_3_fu_785_p1);

assign add_ln840_9_fu_815_p2 = (zext_ln840_5_fu_811_p1 + add_ln840_3_fu_767_p2);

assign add_ln840_fu_745_p2 = (select_ln272_fu_429_p3 + zext_ln840_fu_693_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_718 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op173_write_state3 == 1'b1) & (out0_V_TREADY == 1'b0)))) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_247_p2 == 1'd0)) | ((ap_predicate_op55_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_192 = 'bx;

always @ (*) begin
    ap_predicate_op173_write_state3 = ((icmp_ln290_reg_1024_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_1007_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op55_read_state1 = ((icmp_ln253_fu_259_p2 == 1'd1) & (icmp_ln249_fu_247_p2 == 1'd0));
end

assign i_2_fu_253_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign icmp_ln1039_fu_886_p2 = (($signed(add_ln840_9_reg_1019_pp0_iter1_reg) < $signed(zext_ln1039_fu_882_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_247_p2 = ((ap_sig_allocacmp_i_1 == 10'd1008) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_259_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_423_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_827_p2 = ((sf_2_fu_821_p2 == 32'd12) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_844_p2 = ((nf_fu_838_p2 == 32'd84) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_878_p1 = nf_2_reg_1002;

assign inElem_fu_336_p1 = in0_V_TDATA[9:0];

assign local_temp_V_1_fu_441_p3 = in1_V_TDATA[32'd1];

assign local_temp_V_2_fu_449_p3 = in1_V_TDATA[32'd2];

assign local_temp_V_3_fu_457_p3 = in1_V_TDATA[32'd3];

assign local_temp_V_4_fu_465_p3 = in1_V_TDATA[32'd4];

assign local_temp_V_5_fu_473_p3 = in1_V_TDATA[32'd5];

assign local_temp_V_6_fu_481_p3 = in1_V_TDATA[32'd6];

assign local_temp_V_7_fu_489_p3 = in1_V_TDATA[32'd7];

assign local_temp_V_8_fu_497_p3 = in1_V_TDATA[32'd8];

assign local_temp_V_9_fu_505_p3 = in1_V_TDATA[32'd9];

assign local_temp_V_fu_437_p1 = in1_V_TDATA[0:0];

assign nf_3_fu_850_p3 = ((icmp_ln302_fu_844_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_838_p2);

assign nf_fu_838_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out0_V_TDATA = result_V_fu_891_p2;

assign p_Result_1_fu_529_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd1];

assign p_Result_2_fu_553_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd2];

assign p_Result_3_fu_577_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd3];

assign p_Result_4_fu_601_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd4];

assign p_Result_5_fu_625_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd5];

assign p_Result_6_fu_649_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd6];

assign p_Result_7_fu_673_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd7];

assign p_Result_8_fu_697_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd8];

assign p_Result_9_fu_721_p3 = ap_phi_mux_inElem_1_phi_fu_195_p26[32'd9];

assign p_Result_s_fu_419_p1 = ap_phi_mux_inElem_1_phi_fu_195_p26[0:0];

assign result_V_fu_891_p2 = (icmp_ln1039_fu_886_p2 ^ 1'd1);

assign select_ln272_fu_429_p3 = ((icmp_ln272_fu_423_p2[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_960_fu_104);

assign sf_2_fu_821_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign threshs_address0 = idxprom2_i_fu_878_p1;

assign tmp_fu_305_p13 = ap_sig_allocacmp_sf_1[3:0];

assign trunc_ln257_fu_352_p1 = ap_sig_allocacmp_sf_1[3:0];

assign xor_ln1019_10_fu_633_p2 = (p_Result_5_fu_625_p3 ^ local_temp_V_5_fu_473_p3);

assign xor_ln1019_11_fu_639_p2 = (xor_ln1019_10_fu_633_p2 ^ 1'd1);

assign xor_ln1019_12_fu_657_p2 = (p_Result_6_fu_649_p3 ^ local_temp_V_6_fu_481_p3);

assign xor_ln1019_13_fu_663_p2 = (xor_ln1019_12_fu_657_p2 ^ 1'd1);

assign xor_ln1019_14_fu_681_p2 = (p_Result_7_fu_673_p3 ^ local_temp_V_7_fu_489_p3);

assign xor_ln1019_15_fu_687_p2 = (xor_ln1019_14_fu_681_p2 ^ 1'd1);

assign xor_ln1019_16_fu_705_p2 = (p_Result_8_fu_697_p3 ^ local_temp_V_8_fu_497_p3);

assign xor_ln1019_17_fu_711_p2 = (xor_ln1019_16_fu_705_p2 ^ 1'd1);

assign xor_ln1019_18_fu_729_p2 = (local_temp_V_9_fu_505_p3 ^ 1'd1);

assign xor_ln1019_19_fu_735_p2 = (xor_ln1019_18_fu_729_p2 ^ p_Result_9_fu_721_p3);

assign xor_ln1019_1_fu_519_p2 = (xor_ln1019_fu_513_p2 ^ p_Result_s_fu_419_p1);

assign xor_ln1019_2_fu_537_p2 = (local_temp_V_1_fu_441_p3 ^ 1'd1);

assign xor_ln1019_3_fu_543_p2 = (xor_ln1019_2_fu_537_p2 ^ p_Result_1_fu_529_p3);

assign xor_ln1019_4_fu_561_p2 = (local_temp_V_2_fu_449_p3 ^ 1'd1);

assign xor_ln1019_5_fu_567_p2 = (xor_ln1019_4_fu_561_p2 ^ p_Result_2_fu_553_p3);

assign xor_ln1019_6_fu_585_p2 = (p_Result_3_fu_577_p3 ^ local_temp_V_3_fu_457_p3);

assign xor_ln1019_7_fu_591_p2 = (xor_ln1019_6_fu_585_p2 ^ 1'd1);

assign xor_ln1019_8_fu_609_p2 = (local_temp_V_4_fu_465_p3 ^ 1'd1);

assign xor_ln1019_9_fu_615_p2 = (xor_ln1019_8_fu_609_p2 ^ p_Result_4_fu_601_p3);

assign xor_ln1019_fu_513_p2 = (local_temp_V_fu_437_p1 ^ 1'd1);

assign zext_ln1039_fu_882_p1 = threshs_q0;

assign zext_ln780_1_fu_549_p1 = xor_ln1019_3_fu_543_p2;

assign zext_ln780_2_fu_573_p1 = xor_ln1019_5_fu_567_p2;

assign zext_ln780_3_fu_597_p1 = xor_ln1019_7_fu_591_p2;

assign zext_ln780_4_fu_621_p1 = xor_ln1019_9_fu_615_p2;

assign zext_ln780_5_fu_645_p1 = xor_ln1019_11_fu_639_p2;

assign zext_ln780_6_fu_669_p1 = xor_ln1019_13_fu_663_p2;

assign zext_ln780_7_fu_717_p1 = xor_ln1019_17_fu_711_p2;

assign zext_ln780_fu_525_p1 = xor_ln1019_1_fu_519_p2;

assign zext_ln840_1_fu_741_p1 = xor_ln1019_19_fu_735_p2;

assign zext_ln840_2_fu_763_p1 = add_ln840_2_fu_757_p2;

assign zext_ln840_3_fu_785_p1 = add_ln840_5_fu_779_p2;

assign zext_ln840_4_fu_801_p1 = add_ln840_7_fu_795_p2;

assign zext_ln840_5_fu_811_p1 = add_ln840_8_fu_805_p2;

assign zext_ln840_fu_693_p1 = xor_ln1019_15_fu_687_p2;

endmodule //MVAU_hls_3_Matrix_Vector_Activate_Stream_Batch
