// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_hls_0_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        buf_V_19_load_1,
        buf_V_18_load_1,
        buf_V_17_load_1,
        buf_V_16_load_1,
        buf_V_15_load_1,
        buf_V_14_load_1,
        buf_V_13_load_1,
        buf_V_12_load_1,
        buf_V_11_load_1,
        buf_V_10_load_1,
        buf_V_9_load_1,
        buf_V_8_load_1,
        buf_V_7_load_1,
        buf_V_6_load_1,
        buf_V_5_load_1,
        buf_V_4_load_1,
        buf_V_3_load_1,
        buf_V_2_load_1,
        buf_V_1_load_1,
        buf_V_load_1,
        buf_V_19_address0,
        buf_V_19_ce0,
        buf_V_19_we0,
        buf_V_19_d0,
        zext_ln156,
        buf_V_18_address0,
        buf_V_18_ce0,
        buf_V_18_we0,
        buf_V_18_d0,
        buf_V_17_address0,
        buf_V_17_ce0,
        buf_V_17_we0,
        buf_V_17_d0,
        buf_V_16_address0,
        buf_V_16_ce0,
        buf_V_16_we0,
        buf_V_16_d0,
        buf_V_15_address0,
        buf_V_15_ce0,
        buf_V_15_we0,
        buf_V_15_d0,
        buf_V_14_address0,
        buf_V_14_ce0,
        buf_V_14_we0,
        buf_V_14_d0,
        buf_V_13_address0,
        buf_V_13_ce0,
        buf_V_13_we0,
        buf_V_13_d0,
        buf_V_12_address0,
        buf_V_12_ce0,
        buf_V_12_we0,
        buf_V_12_d0,
        buf_V_11_address0,
        buf_V_11_ce0,
        buf_V_11_we0,
        buf_V_11_d0,
        buf_V_10_address0,
        buf_V_10_ce0,
        buf_V_10_we0,
        buf_V_10_d0,
        buf_V_9_address0,
        buf_V_9_ce0,
        buf_V_9_we0,
        buf_V_9_d0,
        buf_V_8_address0,
        buf_V_8_ce0,
        buf_V_8_we0,
        buf_V_8_d0,
        buf_V_7_address0,
        buf_V_7_ce0,
        buf_V_7_we0,
        buf_V_7_d0,
        buf_V_6_address0,
        buf_V_6_ce0,
        buf_V_6_we0,
        buf_V_6_d0,
        buf_V_5_address0,
        buf_V_5_ce0,
        buf_V_5_we0,
        buf_V_5_d0,
        buf_V_4_address0,
        buf_V_4_ce0,
        buf_V_4_we0,
        buf_V_4_d0,
        buf_V_3_address0,
        buf_V_3_ce0,
        buf_V_3_we0,
        buf_V_3_d0,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_we0,
        buf_V_2_d0,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_we0,
        buf_V_1_d0,
        buf_V_address0,
        buf_V_ce0,
        buf_V_we0,
        buf_V_d0,
        in0_V_TDATA,
        in0_V_TREADY
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input  [7:0] buf_V_19_load_1;
input  [7:0] buf_V_18_load_1;
input  [7:0] buf_V_17_load_1;
input  [7:0] buf_V_16_load_1;
input  [7:0] buf_V_15_load_1;
input  [7:0] buf_V_14_load_1;
input  [7:0] buf_V_13_load_1;
input  [7:0] buf_V_12_load_1;
input  [7:0] buf_V_11_load_1;
input  [7:0] buf_V_10_load_1;
input  [7:0] buf_V_9_load_1;
input  [7:0] buf_V_8_load_1;
input  [7:0] buf_V_7_load_1;
input  [7:0] buf_V_6_load_1;
input  [7:0] buf_V_5_load_1;
input  [7:0] buf_V_4_load_1;
input  [7:0] buf_V_3_load_1;
input  [7:0] buf_V_2_load_1;
input  [7:0] buf_V_1_load_1;
input  [7:0] buf_V_load_1;
output  [3:0] buf_V_19_address0;
output   buf_V_19_ce0;
output   buf_V_19_we0;
output  [7:0] buf_V_19_d0;
input  [3:0] zext_ln156;
output  [3:0] buf_V_18_address0;
output   buf_V_18_ce0;
output   buf_V_18_we0;
output  [7:0] buf_V_18_d0;
output  [3:0] buf_V_17_address0;
output   buf_V_17_ce0;
output   buf_V_17_we0;
output  [7:0] buf_V_17_d0;
output  [3:0] buf_V_16_address0;
output   buf_V_16_ce0;
output   buf_V_16_we0;
output  [7:0] buf_V_16_d0;
output  [3:0] buf_V_15_address0;
output   buf_V_15_ce0;
output   buf_V_15_we0;
output  [7:0] buf_V_15_d0;
output  [3:0] buf_V_14_address0;
output   buf_V_14_ce0;
output   buf_V_14_we0;
output  [7:0] buf_V_14_d0;
output  [3:0] buf_V_13_address0;
output   buf_V_13_ce0;
output   buf_V_13_we0;
output  [7:0] buf_V_13_d0;
output  [3:0] buf_V_12_address0;
output   buf_V_12_ce0;
output   buf_V_12_we0;
output  [7:0] buf_V_12_d0;
output  [3:0] buf_V_11_address0;
output   buf_V_11_ce0;
output   buf_V_11_we0;
output  [7:0] buf_V_11_d0;
output  [3:0] buf_V_10_address0;
output   buf_V_10_ce0;
output   buf_V_10_we0;
output  [7:0] buf_V_10_d0;
output  [3:0] buf_V_9_address0;
output   buf_V_9_ce0;
output   buf_V_9_we0;
output  [7:0] buf_V_9_d0;
output  [3:0] buf_V_8_address0;
output   buf_V_8_ce0;
output   buf_V_8_we0;
output  [7:0] buf_V_8_d0;
output  [3:0] buf_V_7_address0;
output   buf_V_7_ce0;
output   buf_V_7_we0;
output  [7:0] buf_V_7_d0;
output  [3:0] buf_V_6_address0;
output   buf_V_6_ce0;
output   buf_V_6_we0;
output  [7:0] buf_V_6_d0;
output  [3:0] buf_V_5_address0;
output   buf_V_5_ce0;
output   buf_V_5_we0;
output  [7:0] buf_V_5_d0;
output  [3:0] buf_V_4_address0;
output   buf_V_4_ce0;
output   buf_V_4_we0;
output  [7:0] buf_V_4_d0;
output  [3:0] buf_V_3_address0;
output   buf_V_3_ce0;
output   buf_V_3_we0;
output  [7:0] buf_V_3_d0;
output  [3:0] buf_V_2_address0;
output   buf_V_2_ce0;
output   buf_V_2_we0;
output  [7:0] buf_V_2_d0;
output  [3:0] buf_V_1_address0;
output   buf_V_1_ce0;
output   buf_V_1_we0;
output  [7:0] buf_V_1_d0;
output  [3:0] buf_V_address0;
output   buf_V_ce0;
output   buf_V_we0;
output  [7:0] buf_V_d0;
input  [159:0] in0_V_TDATA;
output   in0_V_TREADY;

reg ap_idle;
reg buf_V_19_ce0;
reg buf_V_19_we0;
reg buf_V_18_ce0;
reg buf_V_18_we0;
reg buf_V_17_ce0;
reg buf_V_17_we0;
reg buf_V_16_ce0;
reg buf_V_16_we0;
reg buf_V_15_ce0;
reg buf_V_15_we0;
reg buf_V_14_ce0;
reg buf_V_14_we0;
reg buf_V_13_ce0;
reg buf_V_13_we0;
reg buf_V_12_ce0;
reg buf_V_12_we0;
reg buf_V_11_ce0;
reg buf_V_11_we0;
reg buf_V_10_ce0;
reg buf_V_10_we0;
reg buf_V_9_ce0;
reg buf_V_9_we0;
reg buf_V_8_ce0;
reg buf_V_8_we0;
reg buf_V_7_ce0;
reg buf_V_7_we0;
reg buf_V_6_ce0;
reg buf_V_6_we0;
reg buf_V_5_ce0;
reg buf_V_5_we0;
reg buf_V_4_ce0;
reg buf_V_4_we0;
reg buf_V_3_ce0;
reg buf_V_3_we0;
reg buf_V_2_ce0;
reg buf_V_2_we0;
reg buf_V_1_ce0;
reg buf_V_1_we0;
reg buf_V_ce0;
reg buf_V_we0;
reg in0_V_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln158_fu_810_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
wire   [63:0] zext_ln156_cast_fu_678_p1;
reg   [1:0] kx_fu_202;
wire   [1:0] kx_2_fu_816_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_kx_1;
reg   [7:0] oldMax_V_fu_206;
wire   [7:0] select_ln167_fu_892_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_load;
reg   [7:0] oldMax_V_1_fu_210;
wire   [7:0] select_ln167_1_fu_917_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_1_load;
reg   [7:0] oldMax_V_2_fu_214;
wire   [7:0] select_ln167_2_fu_942_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_2_load;
reg   [7:0] oldMax_V_3_fu_218;
wire   [7:0] select_ln167_3_fu_967_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_3_load;
reg   [7:0] oldMax_V_4_fu_222;
wire   [7:0] select_ln167_4_fu_992_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_4_load;
reg   [7:0] oldMax_V_5_fu_226;
wire   [7:0] select_ln167_5_fu_1017_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_5_load;
reg   [7:0] oldMax_V_6_fu_230;
wire   [7:0] select_ln167_6_fu_1042_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_6_load;
reg   [7:0] oldMax_V_7_fu_234;
wire   [7:0] select_ln167_7_fu_1067_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_7_load;
reg   [7:0] oldMax_V_8_fu_238;
wire   [7:0] select_ln167_8_fu_1092_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_8_load;
reg   [7:0] oldMax_V_9_fu_242;
wire   [7:0] select_ln167_9_fu_1117_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_9_load;
reg   [7:0] oldMax_V_10_fu_246;
wire   [7:0] select_ln167_10_fu_1142_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_10_load;
reg   [7:0] oldMax_V_11_fu_250;
wire   [7:0] select_ln167_11_fu_1167_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_11_load;
reg   [7:0] oldMax_V_12_fu_254;
wire   [7:0] select_ln167_12_fu_1192_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_12_load;
reg   [7:0] oldMax_V_13_fu_258;
wire   [7:0] select_ln167_13_fu_1217_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_13_load;
reg   [7:0] oldMax_V_14_fu_262;
wire   [7:0] select_ln167_14_fu_1242_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_14_load;
reg   [7:0] oldMax_V_15_fu_266;
wire   [7:0] select_ln167_15_fu_1267_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_15_load;
reg   [7:0] oldMax_V_16_fu_270;
wire   [7:0] select_ln167_16_fu_1292_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_16_load;
reg   [7:0] oldMax_V_17_fu_274;
wire   [7:0] select_ln167_17_fu_1317_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_17_load;
reg   [7:0] oldMax_V_18_fu_278;
wire   [7:0] select_ln167_18_fu_1342_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_18_load;
reg   [7:0] oldMax_V_19_fu_282;
wire   [7:0] select_ln167_19_fu_1367_p3;
reg   [7:0] ap_sig_allocacmp_oldMax_V_19_load;
wire   [0:0] icmp_ln158_1_fu_1376_p2;
wire   [7:0] channeldata_V_fu_882_p1;
wire   [0:0] icmp_ln1035_fu_886_p2;
wire   [7:0] channeldata_V_1_fu_901_p4;
wire   [0:0] icmp_ln1035_1_fu_911_p2;
wire   [7:0] channeldata_V_2_fu_926_p4;
wire   [0:0] icmp_ln1035_2_fu_936_p2;
wire   [7:0] channeldata_V_3_fu_951_p4;
wire   [0:0] icmp_ln1035_3_fu_961_p2;
wire   [7:0] channeldata_V_4_fu_976_p4;
wire   [0:0] icmp_ln1035_4_fu_986_p2;
wire   [7:0] channeldata_V_5_fu_1001_p4;
wire   [0:0] icmp_ln1035_5_fu_1011_p2;
wire   [7:0] channeldata_V_6_fu_1026_p4;
wire   [0:0] icmp_ln1035_6_fu_1036_p2;
wire   [7:0] channeldata_V_7_fu_1051_p4;
wire   [0:0] icmp_ln1035_7_fu_1061_p2;
wire   [7:0] channeldata_V_8_fu_1076_p4;
wire   [0:0] icmp_ln1035_8_fu_1086_p2;
wire   [7:0] channeldata_V_9_fu_1101_p4;
wire   [0:0] icmp_ln1035_9_fu_1111_p2;
wire   [7:0] channeldata_V_10_fu_1126_p4;
wire   [0:0] icmp_ln1035_10_fu_1136_p2;
wire   [7:0] channeldata_V_11_fu_1151_p4;
wire   [0:0] icmp_ln1035_11_fu_1161_p2;
wire   [7:0] channeldata_V_12_fu_1176_p4;
wire   [0:0] icmp_ln1035_12_fu_1186_p2;
wire   [7:0] channeldata_V_13_fu_1201_p4;
wire   [0:0] icmp_ln1035_13_fu_1211_p2;
wire   [7:0] channeldata_V_14_fu_1226_p4;
wire   [0:0] icmp_ln1035_14_fu_1236_p2;
wire   [7:0] channeldata_V_15_fu_1251_p4;
wire   [0:0] icmp_ln1035_15_fu_1261_p2;
wire   [7:0] channeldata_V_16_fu_1276_p4;
wire   [0:0] icmp_ln1035_16_fu_1286_p2;
wire   [7:0] channeldata_V_17_fu_1301_p4;
wire   [0:0] icmp_ln1035_17_fu_1311_p2;
wire   [7:0] channeldata_V_18_fu_1326_p4;
wire   [0:0] icmp_ln1035_18_fu_1336_p2;
wire   [7:0] channeldata_V_19_fu_1351_p4;
wire   [0:0] icmp_ln1035_19_fu_1361_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_693;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

StreamingMaxPool_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            kx_fu_202 <= kx_2_fu_816_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kx_fu_202 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_10_fu_246 <= select_ln167_10_fu_1142_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_10_fu_246 <= buf_V_10_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_11_fu_250 <= select_ln167_11_fu_1167_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_11_fu_250 <= buf_V_11_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_12_fu_254 <= select_ln167_12_fu_1192_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_12_fu_254 <= buf_V_12_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_13_fu_258 <= select_ln167_13_fu_1217_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_13_fu_258 <= buf_V_13_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_14_fu_262 <= select_ln167_14_fu_1242_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_14_fu_262 <= buf_V_14_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_15_fu_266 <= select_ln167_15_fu_1267_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_15_fu_266 <= buf_V_15_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_16_fu_270 <= select_ln167_16_fu_1292_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_16_fu_270 <= buf_V_16_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_17_fu_274 <= select_ln167_17_fu_1317_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_17_fu_274 <= buf_V_17_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_18_fu_278 <= select_ln167_18_fu_1342_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_18_fu_278 <= buf_V_18_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_19_fu_282 <= select_ln167_19_fu_1367_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_19_fu_282 <= buf_V_19_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_1_fu_210 <= select_ln167_1_fu_917_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_1_fu_210 <= buf_V_1_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_2_fu_214 <= select_ln167_2_fu_942_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_2_fu_214 <= buf_V_2_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_3_fu_218 <= select_ln167_3_fu_967_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_3_fu_218 <= buf_V_3_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_4_fu_222 <= select_ln167_4_fu_992_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_4_fu_222 <= buf_V_4_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_5_fu_226 <= select_ln167_5_fu_1017_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_5_fu_226 <= buf_V_5_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_6_fu_230 <= select_ln167_6_fu_1042_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_6_fu_230 <= buf_V_6_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_7_fu_234 <= select_ln167_7_fu_1067_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_7_fu_234 <= buf_V_7_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_8_fu_238 <= select_ln167_8_fu_1092_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_8_fu_238 <= buf_V_8_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_9_fu_242 <= select_ln167_9_fu_1117_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_9_fu_242 <= buf_V_9_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_693)) begin
        if ((icmp_ln158_fu_810_p2 == 1'd0)) begin
            oldMax_V_fu_206 <= select_ln167_fu_892_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_fu_206 <= buf_V_load_1;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_810_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_kx_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_kx_1 = kx_fu_202;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_10_load = buf_V_10_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_10_load = oldMax_V_10_fu_246;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_11_load = buf_V_11_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_11_load = oldMax_V_11_fu_250;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_12_load = buf_V_12_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_12_load = oldMax_V_12_fu_254;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_13_load = buf_V_13_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_13_load = oldMax_V_13_fu_258;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_14_load = buf_V_14_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_14_load = oldMax_V_14_fu_262;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_15_load = buf_V_15_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_15_load = oldMax_V_15_fu_266;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_16_load = buf_V_16_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_16_load = oldMax_V_16_fu_270;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_17_load = buf_V_17_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_17_load = oldMax_V_17_fu_274;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_18_load = buf_V_18_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_18_load = oldMax_V_18_fu_278;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_19_load = buf_V_19_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_19_load = oldMax_V_19_fu_282;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_1_load = buf_V_1_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_1_load = oldMax_V_1_fu_210;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_2_load = buf_V_2_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_2_load = oldMax_V_2_fu_214;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_3_load = buf_V_3_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_3_load = oldMax_V_3_fu_218;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_4_load = buf_V_4_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_4_load = oldMax_V_4_fu_222;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_5_load = buf_V_5_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_5_load = oldMax_V_5_fu_226;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_6_load = buf_V_6_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_6_load = oldMax_V_6_fu_230;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_7_load = buf_V_7_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_7_load = oldMax_V_7_fu_234;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_8_load = buf_V_8_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_8_load = oldMax_V_8_fu_238;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_9_load = buf_V_9_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_9_load = oldMax_V_9_fu_242;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_load = buf_V_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_load = oldMax_V_fu_206;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_ce0 = 1'b1;
    end else begin
        buf_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_we0 = 1'b1;
    end else begin
        buf_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_ce0 = 1'b1;
    end else begin
        buf_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_we0 = 1'b1;
    end else begin
        buf_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_ce0 = 1'b1;
    end else begin
        buf_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_we0 = 1'b1;
    end else begin
        buf_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_ce0 = 1'b1;
    end else begin
        buf_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_we0 = 1'b1;
    end else begin
        buf_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_ce0 = 1'b1;
    end else begin
        buf_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_we0 = 1'b1;
    end else begin
        buf_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_ce0 = 1'b1;
    end else begin
        buf_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_we0 = 1'b1;
    end else begin
        buf_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_16_ce0 = 1'b1;
    end else begin
        buf_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_16_we0 = 1'b1;
    end else begin
        buf_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_17_ce0 = 1'b1;
    end else begin
        buf_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_17_we0 = 1'b1;
    end else begin
        buf_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_18_ce0 = 1'b1;
    end else begin
        buf_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_18_we0 = 1'b1;
    end else begin
        buf_V_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_19_ce0 = 1'b1;
    end else begin
        buf_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_19_we0 = 1'b1;
    end else begin
        buf_V_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_we0 = 1'b1;
    end else begin
        buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_we0 = 1'b1;
    end else begin
        buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_ce0 = 1'b1;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_we0 = 1'b1;
    end else begin
        buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_ce0 = 1'b1;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_we0 = 1'b1;
    end else begin
        buf_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_ce0 = 1'b1;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_we0 = 1'b1;
    end else begin
        buf_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_ce0 = 1'b1;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_we0 = 1'b1;
    end else begin
        buf_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_ce0 = 1'b1;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_we0 = 1'b1;
    end else begin
        buf_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_ce0 = 1'b1;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_we0 = 1'b1;
    end else begin
        buf_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_ce0 = 1'b1;
    end else begin
        buf_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_we0 = 1'b1;
    end else begin
        buf_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1376_p2 == 1'd1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_we0 = 1'b1;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_810_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_693 = (~((ap_start_int == 1'b0) | ((icmp_ln158_fu_810_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_V_10_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_10_d0 = ((icmp_ln1035_10_fu_1136_p2[0:0] == 1'b1) ? channeldata_V_10_fu_1126_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign buf_V_11_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_11_d0 = ((icmp_ln1035_11_fu_1161_p2[0:0] == 1'b1) ? channeldata_V_11_fu_1151_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign buf_V_12_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_12_d0 = ((icmp_ln1035_12_fu_1186_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1176_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign buf_V_13_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_13_d0 = ((icmp_ln1035_13_fu_1211_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1201_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign buf_V_14_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_14_d0 = ((icmp_ln1035_14_fu_1236_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1226_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign buf_V_15_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_15_d0 = ((icmp_ln1035_15_fu_1261_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1251_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign buf_V_16_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_16_d0 = ((icmp_ln1035_16_fu_1286_p2[0:0] == 1'b1) ? channeldata_V_16_fu_1276_p4 : ap_sig_allocacmp_oldMax_V_16_load);

assign buf_V_17_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_17_d0 = ((icmp_ln1035_17_fu_1311_p2[0:0] == 1'b1) ? channeldata_V_17_fu_1301_p4 : ap_sig_allocacmp_oldMax_V_17_load);

assign buf_V_18_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_18_d0 = ((icmp_ln1035_18_fu_1336_p2[0:0] == 1'b1) ? channeldata_V_18_fu_1326_p4 : ap_sig_allocacmp_oldMax_V_18_load);

assign buf_V_19_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_19_d0 = ((icmp_ln1035_19_fu_1361_p2[0:0] == 1'b1) ? channeldata_V_19_fu_1351_p4 : ap_sig_allocacmp_oldMax_V_19_load);

assign buf_V_1_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_1_d0 = ((icmp_ln1035_1_fu_911_p2[0:0] == 1'b1) ? channeldata_V_1_fu_901_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign buf_V_2_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_2_d0 = ((icmp_ln1035_2_fu_936_p2[0:0] == 1'b1) ? channeldata_V_2_fu_926_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign buf_V_3_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_3_d0 = ((icmp_ln1035_3_fu_961_p2[0:0] == 1'b1) ? channeldata_V_3_fu_951_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign buf_V_4_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_4_d0 = ((icmp_ln1035_4_fu_986_p2[0:0] == 1'b1) ? channeldata_V_4_fu_976_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign buf_V_5_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_5_d0 = ((icmp_ln1035_5_fu_1011_p2[0:0] == 1'b1) ? channeldata_V_5_fu_1001_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign buf_V_6_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_6_d0 = ((icmp_ln1035_6_fu_1036_p2[0:0] == 1'b1) ? channeldata_V_6_fu_1026_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign buf_V_7_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_7_d0 = ((icmp_ln1035_7_fu_1061_p2[0:0] == 1'b1) ? channeldata_V_7_fu_1051_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign buf_V_8_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_8_d0 = ((icmp_ln1035_8_fu_1086_p2[0:0] == 1'b1) ? channeldata_V_8_fu_1076_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign buf_V_9_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_9_d0 = ((icmp_ln1035_9_fu_1111_p2[0:0] == 1'b1) ? channeldata_V_9_fu_1101_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign buf_V_address0 = zext_ln156_cast_fu_678_p1;

assign buf_V_d0 = ((icmp_ln1035_fu_886_p2[0:0] == 1'b1) ? channeldata_V_fu_882_p1 : ap_sig_allocacmp_oldMax_V_load);

assign channeldata_V_10_fu_1126_p4 = {{in0_V_TDATA[87:80]}};

assign channeldata_V_11_fu_1151_p4 = {{in0_V_TDATA[95:88]}};

assign channeldata_V_12_fu_1176_p4 = {{in0_V_TDATA[103:96]}};

assign channeldata_V_13_fu_1201_p4 = {{in0_V_TDATA[111:104]}};

assign channeldata_V_14_fu_1226_p4 = {{in0_V_TDATA[119:112]}};

assign channeldata_V_15_fu_1251_p4 = {{in0_V_TDATA[127:120]}};

assign channeldata_V_16_fu_1276_p4 = {{in0_V_TDATA[135:128]}};

assign channeldata_V_17_fu_1301_p4 = {{in0_V_TDATA[143:136]}};

assign channeldata_V_18_fu_1326_p4 = {{in0_V_TDATA[151:144]}};

assign channeldata_V_19_fu_1351_p4 = {{in0_V_TDATA[159:152]}};

assign channeldata_V_1_fu_901_p4 = {{in0_V_TDATA[15:8]}};

assign channeldata_V_2_fu_926_p4 = {{in0_V_TDATA[23:16]}};

assign channeldata_V_3_fu_951_p4 = {{in0_V_TDATA[31:24]}};

assign channeldata_V_4_fu_976_p4 = {{in0_V_TDATA[39:32]}};

assign channeldata_V_5_fu_1001_p4 = {{in0_V_TDATA[47:40]}};

assign channeldata_V_6_fu_1026_p4 = {{in0_V_TDATA[55:48]}};

assign channeldata_V_7_fu_1051_p4 = {{in0_V_TDATA[63:56]}};

assign channeldata_V_8_fu_1076_p4 = {{in0_V_TDATA[71:64]}};

assign channeldata_V_9_fu_1101_p4 = {{in0_V_TDATA[79:72]}};

assign channeldata_V_fu_882_p1 = in0_V_TDATA[7:0];

assign icmp_ln1035_10_fu_1136_p2 = ((channeldata_V_10_fu_1126_p4 > ap_sig_allocacmp_oldMax_V_10_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_11_fu_1161_p2 = ((channeldata_V_11_fu_1151_p4 > ap_sig_allocacmp_oldMax_V_11_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_12_fu_1186_p2 = ((channeldata_V_12_fu_1176_p4 > ap_sig_allocacmp_oldMax_V_12_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_13_fu_1211_p2 = ((channeldata_V_13_fu_1201_p4 > ap_sig_allocacmp_oldMax_V_13_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_14_fu_1236_p2 = ((channeldata_V_14_fu_1226_p4 > ap_sig_allocacmp_oldMax_V_14_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_15_fu_1261_p2 = ((channeldata_V_15_fu_1251_p4 > ap_sig_allocacmp_oldMax_V_15_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_16_fu_1286_p2 = ((channeldata_V_16_fu_1276_p4 > ap_sig_allocacmp_oldMax_V_16_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_17_fu_1311_p2 = ((channeldata_V_17_fu_1301_p4 > ap_sig_allocacmp_oldMax_V_17_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_18_fu_1336_p2 = ((channeldata_V_18_fu_1326_p4 > ap_sig_allocacmp_oldMax_V_18_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_19_fu_1361_p2 = ((channeldata_V_19_fu_1351_p4 > ap_sig_allocacmp_oldMax_V_19_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_911_p2 = ((channeldata_V_1_fu_901_p4 > ap_sig_allocacmp_oldMax_V_1_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_936_p2 = ((channeldata_V_2_fu_926_p4 > ap_sig_allocacmp_oldMax_V_2_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_3_fu_961_p2 = ((channeldata_V_3_fu_951_p4 > ap_sig_allocacmp_oldMax_V_3_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_4_fu_986_p2 = ((channeldata_V_4_fu_976_p4 > ap_sig_allocacmp_oldMax_V_4_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_5_fu_1011_p2 = ((channeldata_V_5_fu_1001_p4 > ap_sig_allocacmp_oldMax_V_5_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_6_fu_1036_p2 = ((channeldata_V_6_fu_1026_p4 > ap_sig_allocacmp_oldMax_V_6_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_7_fu_1061_p2 = ((channeldata_V_7_fu_1051_p4 > ap_sig_allocacmp_oldMax_V_7_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_8_fu_1086_p2 = ((channeldata_V_8_fu_1076_p4 > ap_sig_allocacmp_oldMax_V_8_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_9_fu_1111_p2 = ((channeldata_V_9_fu_1101_p4 > ap_sig_allocacmp_oldMax_V_9_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_886_p2 = ((channeldata_V_fu_882_p1 > ap_sig_allocacmp_oldMax_V_load) ? 1'b1 : 1'b0);

assign icmp_ln158_1_fu_1376_p2 = ((kx_2_fu_816_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_810_p2 = ((ap_sig_allocacmp_kx_1 == 2'd2) ? 1'b1 : 1'b0);

assign kx_2_fu_816_p2 = (ap_sig_allocacmp_kx_1 + 2'd1);

assign select_ln167_10_fu_1142_p3 = ((icmp_ln1035_10_fu_1136_p2[0:0] == 1'b1) ? channeldata_V_10_fu_1126_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign select_ln167_11_fu_1167_p3 = ((icmp_ln1035_11_fu_1161_p2[0:0] == 1'b1) ? channeldata_V_11_fu_1151_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign select_ln167_12_fu_1192_p3 = ((icmp_ln1035_12_fu_1186_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1176_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign select_ln167_13_fu_1217_p3 = ((icmp_ln1035_13_fu_1211_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1201_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign select_ln167_14_fu_1242_p3 = ((icmp_ln1035_14_fu_1236_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1226_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign select_ln167_15_fu_1267_p3 = ((icmp_ln1035_15_fu_1261_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1251_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign select_ln167_16_fu_1292_p3 = ((icmp_ln1035_16_fu_1286_p2[0:0] == 1'b1) ? channeldata_V_16_fu_1276_p4 : ap_sig_allocacmp_oldMax_V_16_load);

assign select_ln167_17_fu_1317_p3 = ((icmp_ln1035_17_fu_1311_p2[0:0] == 1'b1) ? channeldata_V_17_fu_1301_p4 : ap_sig_allocacmp_oldMax_V_17_load);

assign select_ln167_18_fu_1342_p3 = ((icmp_ln1035_18_fu_1336_p2[0:0] == 1'b1) ? channeldata_V_18_fu_1326_p4 : ap_sig_allocacmp_oldMax_V_18_load);

assign select_ln167_19_fu_1367_p3 = ((icmp_ln1035_19_fu_1361_p2[0:0] == 1'b1) ? channeldata_V_19_fu_1351_p4 : ap_sig_allocacmp_oldMax_V_19_load);

assign select_ln167_1_fu_917_p3 = ((icmp_ln1035_1_fu_911_p2[0:0] == 1'b1) ? channeldata_V_1_fu_901_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign select_ln167_2_fu_942_p3 = ((icmp_ln1035_2_fu_936_p2[0:0] == 1'b1) ? channeldata_V_2_fu_926_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign select_ln167_3_fu_967_p3 = ((icmp_ln1035_3_fu_961_p2[0:0] == 1'b1) ? channeldata_V_3_fu_951_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign select_ln167_4_fu_992_p3 = ((icmp_ln1035_4_fu_986_p2[0:0] == 1'b1) ? channeldata_V_4_fu_976_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign select_ln167_5_fu_1017_p3 = ((icmp_ln1035_5_fu_1011_p2[0:0] == 1'b1) ? channeldata_V_5_fu_1001_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign select_ln167_6_fu_1042_p3 = ((icmp_ln1035_6_fu_1036_p2[0:0] == 1'b1) ? channeldata_V_6_fu_1026_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign select_ln167_7_fu_1067_p3 = ((icmp_ln1035_7_fu_1061_p2[0:0] == 1'b1) ? channeldata_V_7_fu_1051_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign select_ln167_8_fu_1092_p3 = ((icmp_ln1035_8_fu_1086_p2[0:0] == 1'b1) ? channeldata_V_8_fu_1076_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign select_ln167_9_fu_1117_p3 = ((icmp_ln1035_9_fu_1111_p2[0:0] == 1'b1) ? channeldata_V_9_fu_1101_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign select_ln167_fu_892_p3 = ((icmp_ln1035_fu_886_p2[0:0] == 1'b1) ? channeldata_V_fu_882_p1 : ap_sig_allocacmp_oldMax_V_load);

assign zext_ln156_cast_fu_678_p1 = zext_ln156;

endmodule //StreamingMaxPool_hls_0_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6
