-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingMaxPool_hls_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in0_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in0_V_TVALID : IN STD_LOGIC;
    in0_V_TREADY : OUT STD_LOGIC;
    out0_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    out0_V_TVALID : OUT STD_LOGIC;
    out0_V_TREADY : IN STD_LOGIC );
end;


architecture behav of StreamingMaxPool_hls_1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "StreamingMaxPool_hls_1_StreamingMaxPool_hls_1,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.518500,HLS_SYN_LAT=179,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=132,HLS_SYN_LUT=557,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal buf_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal buf_V_ce0 : STD_LOGIC;
    signal buf_V_we0 : STD_LOGIC;
    signal buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal buf_V_ce1 : STD_LOGIC;
    signal buf_V_we1 : STD_LOGIC;
    signal buf_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_idle : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_ready : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_in0_V_TREADY : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce0 : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_we0 : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce1 : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_idle : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_ready : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TREADY : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_ce0 : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_we0 : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TVALID : STD_LOGIC;
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln78_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal yp_fu_58 : STD_LOGIC_VECTOR (2 downto 0);
    signal yp_2_fu_146_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal regslice_both_out0_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal regslice_both_in0_V_U_apdone_blk : STD_LOGIC;
    signal in0_V_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal in0_V_TVALID_int_regslice : STD_LOGIC;
    signal in0_V_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in0_V_U_ack_in : STD_LOGIC;
    signal out0_V_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out0_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component StreamingMaxPool_hls_1_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in0_V_TVALID : IN STD_LOGIC;
        in0_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        in0_V_TREADY : OUT STD_LOGIC;
        buf_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        buf_V_ce0 : OUT STD_LOGIC;
        buf_V_we0 : OUT STD_LOGIC;
        buf_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        buf_V_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        buf_V_ce1 : OUT STD_LOGIC;
        buf_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component StreamingMaxPool_hls_1_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out0_V_TREADY : IN STD_LOGIC;
        buf_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        buf_V_ce0 : OUT STD_LOGIC;
        buf_V_we0 : OUT STD_LOGIC;
        buf_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        buf_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        out0_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        out0_V_TVALID : OUT STD_LOGIC );
    end component;


    component StreamingMaxPool_hls_1_buf_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component StreamingMaxPool_hls_1_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    buf_V_U : component StreamingMaxPool_hls_1_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buf_V_address0,
        ce0 => buf_V_ce0,
        we0 => buf_V_we0,
        d0 => buf_V_d0,
        q0 => buf_V_q0,
        address1 => buf_V_address1,
        ce1 => buf_V_ce1,
        we1 => buf_V_we1,
        d1 => ap_const_lv16_0,
        q1 => buf_V_q1);

    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118 : component StreamingMaxPool_hls_1_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start,
        ap_done => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done,
        ap_idle => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_idle,
        ap_ready => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_ready,
        in0_V_TVALID => in0_V_TVALID_int_regslice,
        in0_V_TDATA => in0_V_TDATA_int_regslice,
        in0_V_TREADY => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_in0_V_TREADY,
        buf_V_address0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address0,
        buf_V_ce0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce0,
        buf_V_we0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_we0,
        buf_V_d0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_d0,
        buf_V_address1 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address1,
        buf_V_ce1 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce1,
        buf_V_q1 => buf_V_q1);

    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125 : component StreamingMaxPool_hls_1_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start,
        ap_done => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done,
        ap_idle => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_idle,
        ap_ready => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_ready,
        out0_V_TREADY => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TREADY,
        buf_V_address0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_address0,
        buf_V_ce0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_ce0,
        buf_V_we0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_we0,
        buf_V_d0 => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_d0,
        buf_V_q0 => buf_V_q0,
        out0_V_TDATA => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TDATA,
        out0_V_TVALID => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TVALID);

    regslice_both_in0_V_U : component StreamingMaxPool_hls_1_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_V_TDATA,
        vld_in => in0_V_TVALID,
        ack_in => regslice_both_in0_V_U_ack_in,
        data_out => in0_V_TDATA_int_regslice,
        vld_out => in0_V_TVALID_int_regslice,
        ack_out => in0_V_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_U_apdone_blk);

    regslice_both_out0_V_U : component StreamingMaxPool_hls_1_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TDATA,
        vld_in => grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TVALID,
        ack_in => out0_V_TREADY_int_regslice,
        data_out => out0_V_TDATA,
        vld_out => regslice_both_out0_V_U_vld_out,
        ack_out => out0_V_TREADY,
        apdone_blk => regslice_both_out0_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln78_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_ready = ap_const_logic_1)) then 
                    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    yp_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                yp_fu_58 <= ap_const_lv3_0;
            elsif (((icmp_ln78_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                yp_fu_58 <= yp_2_fu_146_p2;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done, grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done, ap_CS_fsm, ap_CS_fsm_state4, icmp_ln78_fu_140_p2, ap_CS_fsm_state5, ap_CS_fsm_state8, regslice_both_out0_V_U_apdone_blk, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln78_fu_140_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (regslice_both_out0_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done)
    begin
        if ((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done)
    begin
        if ((grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(regslice_both_out0_V_U_apdone_blk)
    begin
        if ((regslice_both_out0_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    buf_V_address0_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address0, grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_address0, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buf_V_address0 <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_address0 <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            buf_V_address0 <= ap_const_lv64_0(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_address0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_address0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address0;
        else 
            buf_V_address0 <= "XXX";
        end if; 
    end process;


    buf_V_address1_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address1, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buf_V_address1 <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_V_address1 <= ap_const_lv64_1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_address1 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_address1;
        else 
            buf_V_address1 <= "XXX";
        end if; 
    end process;


    buf_V_ce0_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce0, grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_ce0, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_ce0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_ce0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce0;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce1, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buf_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_ce1 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_ce1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d0_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_d0, grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_d0, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_d0 <= ap_const_lv16_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_d0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_d0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_d0;
        else 
            buf_V_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_V_we0_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_we0, grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_we0, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            buf_V_we0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_buf_V_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            buf_V_we0 <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_buf_V_we0;
        else 
            buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_we1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buf_V_we1 <= ap_const_logic_1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_ap_start_reg;
    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_ap_start_reg;
    grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_90_6_fu_125_out0_V_TREADY <= (out0_V_TREADY_int_regslice and ap_CS_fsm_state8);
    icmp_ln78_fu_140_p2 <= "1" when (yp_fu_58 = ap_const_lv3_5) else "0";
    in0_V_TREADY <= regslice_both_in0_V_U_ack_in;

    in0_V_TREADY_int_regslice_assign_proc : process(grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_in0_V_TREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in0_V_TREADY_int_regslice <= grp_StreamingMaxPool_hls_1_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5_fu_118_in0_V_TREADY;
        else 
            in0_V_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out0_V_TVALID <= regslice_both_out0_V_U_vld_out;
    yp_2_fu_146_p2 <= std_logic_vector(unsigned(yp_fu_58) + unsigned(ap_const_lv3_1));
end behav;
