// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_0_Matrix_Vector_Activate_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out0_V_TREADY;
input  [199:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out0_V_TDATA;
output   out0_V_TVALID;

reg ap_idle;
reg in0_V_TREADY;
reg out0_V_TVALID;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] icmp_ln123_fu_179_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln123_reg_2162;
wire   [0:0] icmp_ln123_reg_2162_pp0_iter0_reg;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
wire   [0:0] result_V_fu_2099_p2;
reg   [0:0] result_V_reg_2166;
wire   [0:0] result_V_1_fu_2105_p2;
reg   [0:0] result_V_1_reg_2171;
wire   [0:0] result_V_2_fu_2111_p2;
reg   [0:0] result_V_2_reg_2176;
wire   [0:0] result_V_3_fu_2117_p2;
reg   [0:0] result_V_3_reg_2181;
wire   [0:0] result_V_4_fu_2123_p2;
reg   [0:0] result_V_4_reg_2186;
wire   [0:0] result_V_5_fu_2129_p2;
reg   [0:0] result_V_5_reg_2191;
reg   [9:0] i_fu_154;
wire   [9:0] i_2_fu_185_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
wire   [7:0] r_V_fu_191_p1;
wire  signed [8:0] sext_ln1494_fu_195_p1;
wire  signed [7:0] r_V_1_fu_205_p4;
wire  signed [7:0] r_V_2_fu_223_p4;
wire  signed [7:0] r_V_3_fu_241_p4;
wire  signed [7:0] r_V_4_fu_255_p4;
wire  signed [8:0] sext_ln1494_1_fu_265_p1;
wire   [8:0] ret_V_1_fu_269_p2;
wire  signed [7:0] r_V_5_fu_279_p4;
wire  signed [8:0] sext_ln1494_2_fu_289_p1;
wire  signed [7:0] r_V_6_fu_299_p4;
wire  signed [8:0] sext_ln1494_3_fu_309_p1;
wire   [8:0] ret_V_3_fu_313_p2;
wire  signed [7:0] r_V_7_fu_323_p4;
wire  signed [8:0] sext_ln1494_4_fu_333_p1;
wire   [8:0] ret_V_4_fu_337_p2;
wire  signed [7:0] r_V_8_fu_347_p4;
wire  signed [8:0] sext_ln1494_5_fu_357_p1;
wire   [8:0] ret_V_5_fu_361_p2;
wire  signed [7:0] r_V_9_fu_371_p4;
wire  signed [8:0] sext_ln1494_6_fu_381_p1;
wire   [8:0] ret_V_6_fu_385_p2;
wire  signed [7:0] r_V_10_fu_395_p4;
wire  signed [8:0] sext_ln1494_7_fu_405_p1;
wire   [8:0] ret_V_7_fu_409_p2;
wire  signed [7:0] r_V_11_fu_419_p4;
wire  signed [8:0] sext_ln1494_8_fu_429_p1;
wire   [8:0] ret_V_8_fu_433_p2;
wire  signed [7:0] r_V_12_fu_443_p4;
wire  signed [8:0] sext_ln1494_9_fu_453_p1;
wire   [8:0] ret_V_9_fu_457_p2;
wire  signed [7:0] r_V_13_fu_467_p4;
wire  signed [8:0] sext_ln1494_10_fu_477_p1;
wire   [8:0] ret_V_10_fu_481_p2;
wire  signed [7:0] r_V_14_fu_491_p4;
wire  signed [8:0] sext_ln1494_11_fu_501_p1;
wire   [8:0] ret_V_11_fu_505_p2;
wire  signed [7:0] r_V_15_fu_515_p4;
wire  signed [8:0] sext_ln1494_12_fu_525_p1;
wire   [8:0] ret_V_12_fu_529_p2;
wire  signed [7:0] r_V_16_fu_539_p4;
wire  signed [8:0] sext_ln1494_13_fu_549_p1;
wire   [8:0] ret_V_13_fu_553_p2;
wire  signed [7:0] r_V_17_fu_563_p4;
wire  signed [8:0] sext_ln1494_14_fu_573_p1;
wire   [8:0] ret_V_14_fu_577_p2;
wire  signed [7:0] r_V_18_fu_587_p4;
wire  signed [8:0] sext_ln1494_15_fu_597_p1;
wire   [8:0] ret_V_15_fu_601_p2;
wire  signed [7:0] r_V_19_fu_611_p4;
wire  signed [8:0] sext_ln1494_16_fu_621_p1;
wire   [7:0] r_V_20_fu_631_p4;
wire  signed [7:0] r_V_21_fu_645_p4;
wire  signed [7:0] r_V_22_fu_663_p4;
wire  signed [7:0] r_V_23_fu_681_p4;
wire  signed [7:0] r_V_24_fu_695_p4;
wire  signed [8:0] sext_ln1494_17_fu_705_p1;
wire  signed [8:0] sext_ln628_1_fu_219_p1;
wire   [8:0] sub_ln840_fu_715_p2;
wire   [8:0] ret_V_2_fu_293_p2;
wire  signed [9:0] sext_ln840_8_fu_729_p1;
wire  signed [9:0] sext_ln840_7_fu_725_p1;
wire   [9:0] sub_ln840_3_fu_733_p2;
wire  signed [9:0] sext_ln840_6_fu_721_p1;
wire   [9:0] add_ln840_fu_739_p2;
wire  signed [9:0] sext_ln628_6_fu_367_p1;
wire  signed [9:0] sext_ln840_10_fu_749_p1;
wire   [9:0] sub_ln840_4_fu_753_p2;
wire  signed [9:0] sext_ln628_4_fu_319_p1;
wire   [9:0] add_ln840_1_fu_759_p2;
wire  signed [10:0] sext_ln840_11_fu_765_p1;
wire  signed [10:0] sext_ln840_9_fu_745_p1;
wire   [10:0] add_ln840_2_fu_769_p2;
wire  signed [9:0] sext_ln628_9_fu_439_p1;
wire  signed [9:0] sext_ln840_13_fu_779_p1;
wire   [9:0] sub_ln840_5_fu_783_p2;
wire  signed [9:0] sext_ln628_7_fu_391_p1;
wire   [9:0] add_ln840_3_fu_789_p2;
wire  signed [9:0] sext_ln628_12_fu_511_p1;
wire  signed [9:0] sext_ln840_15_fu_799_p1;
wire   [9:0] sub_ln840_6_fu_803_p2;
wire  signed [9:0] sext_ln628_10_fu_463_p1;
wire   [9:0] add_ln840_4_fu_809_p2;
wire  signed [10:0] sext_ln840_16_fu_815_p1;
wire  signed [10:0] sext_ln840_14_fu_795_p1;
wire   [10:0] add_ln840_5_fu_819_p2;
wire  signed [11:0] sext_ln840_17_fu_825_p1;
wire  signed [11:0] sext_ln840_12_fu_775_p1;
wire   [11:0] add_ln840_6_fu_829_p2;
wire  signed [9:0] sext_ln628_15_fu_583_p1;
wire  signed [9:0] sext_ln840_19_fu_839_p1;
wire   [9:0] sub_ln840_7_fu_843_p2;
wire  signed [9:0] sext_ln628_13_fu_535_p1;
wire   [9:0] add_ln840_7_fu_849_p2;
wire   [8:0] ret_V_17_fu_709_p2;
wire  signed [9:0] sext_ln840_22_fu_863_p1;
wire  signed [9:0] sext_ln840_21_fu_859_p1;
wire   [9:0] sub_ln840_8_fu_867_p2;
wire  signed [9:0] sext_ln628_16_fu_607_p1;
wire   [9:0] add_ln840_8_fu_873_p2;
wire  signed [10:0] sext_ln840_23_fu_879_p1;
wire  signed [10:0] sext_ln840_20_fu_855_p1;
wire   [10:0] add_ln840_9_fu_883_p2;
wire  signed [8:0] sext_ln840_1_fu_251_p1;
wire  signed [8:0] sext_ln840_2_fu_641_p1;
wire   [8:0] add_ln840_10_fu_893_p2;
wire  signed [9:0] sext_ln840_25_fu_899_p1;
wire  signed [9:0] sext_ln628_2_fu_237_p1;
wire   [9:0] add_ln840_11_fu_903_p2;
wire  signed [8:0] sext_ln840_4_fu_673_p1;
wire  signed [8:0] sext_ln840_5_fu_691_p1;
wire   [8:0] add_ln840_12_fu_913_p2;
wire  signed [9:0] sext_ln840_27_fu_919_p1;
wire  signed [9:0] sext_ln628_17_fu_659_p1;
wire   [9:0] add_ln840_13_fu_923_p2;
wire  signed [10:0] sext_ln840_28_fu_929_p1;
wire  signed [10:0] sext_ln840_26_fu_909_p1;
wire   [10:0] add_ln840_14_fu_933_p2;
wire  signed [11:0] sext_ln840_29_fu_939_p1;
wire  signed [11:0] sext_ln840_24_fu_889_p1;
wire   [11:0] add_ln840_15_fu_943_p2;
wire  signed [12:0] sext_ln840_30_fu_949_p1;
wire  signed [12:0] sext_ln840_18_fu_835_p1;
wire  signed [8:0] sext_ln840_fu_233_p1;
wire   [8:0] ret_V_18_fu_959_p2;
wire   [8:0] ret_V_fu_199_p2;
wire  signed [9:0] sext_ln840_32_fu_969_p1;
wire  signed [9:0] sext_ln628_fu_215_p1;
wire   [9:0] sub_ln840_1_fu_973_p2;
wire  signed [9:0] sext_ln840_31_fu_965_p1;
wire   [8:0] ret_V_19_fu_989_p2;
wire  signed [8:0] sext_ln840_3_fu_655_p1;
wire   [8:0] ret_V_20_fu_999_p2;
wire   [9:0] add_ln840_17_fu_979_p2;
wire  signed [10:0] sext_ln840_35_fu_1019_p1;
wire  signed [10:0] sext_ln840_34_fu_1015_p1;
wire  signed [9:0] sext_ln628_8_fu_415_p1;
wire   [9:0] sub_ln840_10_fu_1029_p2;
wire   [9:0] add_ln840_18_fu_1035_p2;
wire  signed [10:0] sext_ln840_36_fu_1041_p1;
wire   [10:0] sub_ln840_9_fu_1023_p2;
wire   [10:0] add_ln840_19_fu_1045_p2;
wire  signed [9:0] sext_ln840_38_fu_1055_p1;
wire   [9:0] sub_ln840_11_fu_1059_p2;
wire   [9:0] add_ln840_20_fu_1065_p2;
wire  signed [9:0] sext_ln1494_18_fu_995_p1;
wire  signed [9:0] sext_ln840_40_fu_1075_p1;
wire   [9:0] sub_ln840_12_fu_1079_p2;
wire  signed [9:0] sext_ln628_14_fu_559_p1;
wire   [9:0] add_ln840_21_fu_1085_p2;
wire  signed [10:0] sext_ln840_41_fu_1091_p1;
wire  signed [10:0] sext_ln840_39_fu_1071_p1;
wire   [10:0] add_ln840_22_fu_1095_p2;
wire  signed [11:0] sext_ln840_42_fu_1101_p1;
wire  signed [11:0] sext_ln840_37_fu_1051_p1;
wire   [11:0] add_ln840_23_fu_1105_p2;
wire   [8:0] sub_ln840_13_fu_1115_p2;
wire  signed [9:0] sext_ln840_44_fu_1121_p1;
wire   [9:0] sub_ln840_14_fu_1125_p2;
wire   [8:0] add_ln840_24_fu_1135_p2;
wire  signed [9:0] sext_ln840_46_fu_1141_p1;
wire   [9:0] add_ln840_25_fu_1145_p2;
wire  signed [10:0] sext_ln840_47_fu_1151_p1;
wire  signed [10:0] sext_ln840_45_fu_1131_p1;
wire   [10:0] add_ln840_26_fu_1155_p2;
wire   [8:0] add_ln840_27_fu_1165_p2;
wire  signed [9:0] sext_ln840_49_fu_1171_p1;
wire   [9:0] add_ln840_28_fu_1175_p2;
wire   [8:0] add_ln840_29_fu_1185_p2;
wire  signed [9:0] sext_ln840_51_fu_1191_p1;
wire   [9:0] add_ln840_30_fu_1195_p2;
wire  signed [10:0] sext_ln840_52_fu_1201_p1;
wire  signed [10:0] sext_ln840_50_fu_1181_p1;
wire   [10:0] add_ln840_31_fu_1205_p2;
wire  signed [11:0] sext_ln840_53_fu_1211_p1;
wire  signed [11:0] sext_ln840_48_fu_1161_p1;
wire   [11:0] add_ln840_32_fu_1215_p2;
wire  signed [12:0] sext_ln840_54_fu_1221_p1;
wire  signed [12:0] sext_ln840_43_fu_1111_p1;
wire  signed [10:0] sext_ln840_56_fu_1241_p1;
wire  signed [9:0] sext_ln840_57_fu_1251_p1;
wire   [9:0] sub_ln840_16_fu_1255_p2;
wire  signed [9:0] sext_ln628_3_fu_275_p1;
wire   [9:0] add_ln840_34_fu_1261_p2;
wire  signed [10:0] sext_ln840_58_fu_1267_p1;
wire   [10:0] sub_ln840_15_fu_1245_p2;
wire   [10:0] add_ln840_35_fu_1271_p2;
wire  signed [9:0] sext_ln840_33_fu_985_p1;
wire   [9:0] sub_ln840_17_fu_1281_p2;
wire  signed [9:0] sext_ln628_5_fu_343_p1;
wire   [9:0] add_ln840_36_fu_1287_p2;
wire  signed [9:0] sext_ln628_11_fu_487_p1;
wire  signed [9:0] sext_ln840_61_fu_1297_p1;
wire   [9:0] sub_ln840_18_fu_1301_p2;
wire   [9:0] add_ln840_37_fu_1307_p2;
wire  signed [10:0] sext_ln840_62_fu_1313_p1;
wire  signed [10:0] sext_ln840_60_fu_1293_p1;
wire   [10:0] add_ln840_38_fu_1317_p2;
wire  signed [11:0] sext_ln840_63_fu_1323_p1;
wire  signed [11:0] sext_ln840_59_fu_1277_p1;
wire   [11:0] add_ln840_39_fu_1327_p2;
wire   [8:0] add_ln840_40_fu_1337_p2;
wire  signed [9:0] sext_ln840_66_fu_1347_p1;
wire  signed [9:0] sext_ln840_65_fu_1343_p1;
wire   [9:0] sub_ln840_19_fu_1351_p2;
wire   [8:0] add_ln840_41_fu_1361_p2;
wire  signed [9:0] sext_ln840_68_fu_1367_p1;
wire   [9:0] add_ln840_42_fu_1371_p2;
wire  signed [10:0] sext_ln840_69_fu_1377_p1;
wire  signed [10:0] sext_ln840_67_fu_1357_p1;
wire   [10:0] add_ln840_43_fu_1381_p2;
wire   [8:0] add_ln840_44_fu_1391_p2;
wire  signed [9:0] sext_ln840_71_fu_1397_p1;
wire   [9:0] add_ln840_45_fu_1401_p2;
wire  signed [9:0] sext_ln628_18_fu_677_p1;
wire   [9:0] add_ln840_46_fu_1411_p2;
wire  signed [10:0] sext_ln840_73_fu_1417_p1;
wire  signed [10:0] sext_ln840_72_fu_1407_p1;
wire   [10:0] add_ln840_47_fu_1421_p2;
wire  signed [11:0] sext_ln840_74_fu_1427_p1;
wire  signed [11:0] sext_ln840_70_fu_1387_p1;
wire   [11:0] add_ln840_48_fu_1431_p2;
wire  signed [12:0] sext_ln840_75_fu_1437_p1;
wire  signed [12:0] sext_ln840_64_fu_1333_p1;
wire   [8:0] add_ln840_50_fu_1447_p2;
wire  signed [9:0] sext_ln840_77_fu_1463_p1;
wire   [9:0] sub_ln840_20_fu_1467_p2;
wire  signed [9:0] sext_ln840_76_fu_1453_p1;
wire   [9:0] add_ln840_51_fu_1473_p2;
wire  signed [9:0] sext_ln840_79_fu_1483_p1;
wire   [9:0] sub_ln840_21_fu_1487_p2;
wire   [9:0] add_ln840_52_fu_1493_p2;
wire  signed [10:0] sext_ln840_80_fu_1499_p1;
wire  signed [10:0] sext_ln840_78_fu_1479_p1;
wire   [10:0] add_ln840_53_fu_1503_p2;
wire   [9:0] sub_ln840_22_fu_1513_p2;
wire   [9:0] add_ln840_54_fu_1519_p2;
wire   [8:0] sub_ln840_23_fu_1529_p2;
wire  signed [9:0] sext_ln840_83_fu_1535_p1;
wire   [9:0] sub_ln840_24_fu_1539_p2;
wire  signed [10:0] sext_ln840_84_fu_1545_p1;
wire  signed [10:0] sext_ln840_82_fu_1525_p1;
wire   [10:0] add_ln840_55_fu_1549_p2;
wire  signed [11:0] sext_ln840_85_fu_1555_p1;
wire  signed [11:0] sext_ln840_81_fu_1509_p1;
wire   [11:0] add_ln840_56_fu_1559_p2;
wire   [8:0] add_ln840_57_fu_1569_p2;
wire  signed [9:0] sext_ln840_87_fu_1575_p1;
wire   [9:0] add_ln840_58_fu_1579_p2;
wire   [8:0] add_ln840_59_fu_1589_p2;
wire  signed [9:0] sext_ln840_89_fu_1595_p1;
wire   [9:0] add_ln840_60_fu_1599_p2;
wire  signed [10:0] sext_ln840_90_fu_1605_p1;
wire  signed [10:0] sext_ln840_88_fu_1585_p1;
wire   [10:0] add_ln840_61_fu_1609_p2;
wire   [8:0] add_ln840_62_fu_1619_p2;
wire  signed [9:0] sext_ln840_92_fu_1625_p1;
wire  signed [9:0] sext_ln840_55_fu_1237_p1;
wire   [9:0] add_ln840_63_fu_1629_p2;
wire   [8:0] add_ln840_64_fu_1639_p2;
wire  signed [9:0] sext_ln840_94_fu_1645_p1;
wire   [9:0] add_ln840_65_fu_1649_p2;
wire  signed [10:0] sext_ln840_95_fu_1655_p1;
wire  signed [10:0] sext_ln840_93_fu_1635_p1;
wire   [10:0] add_ln840_66_fu_1659_p2;
wire  signed [11:0] sext_ln840_96_fu_1665_p1;
wire  signed [11:0] sext_ln840_91_fu_1615_p1;
wire   [11:0] add_ln840_67_fu_1669_p2;
wire  signed [12:0] sext_ln840_97_fu_1675_p1;
wire  signed [12:0] sext_ln840_86_fu_1565_p1;
wire   [9:0] sub_ln840_25_fu_1685_p2;
wire   [9:0] add_ln840_69_fu_1691_p2;
wire  signed [10:0] sext_ln840_98_fu_1697_p1;
wire   [10:0] add_ln840_70_fu_1701_p2;
wire   [9:0] sub_ln840_26_fu_1711_p2;
wire   [9:0] add_ln840_71_fu_1717_p2;
wire   [8:0] ret_V_23_fu_1457_p2;
wire  signed [9:0] sext_ln840_101_fu_1727_p1;
wire   [9:0] sub_ln840_27_fu_1731_p2;
wire  signed [9:0] sext_ln1494_19_fu_1005_p1;
wire   [9:0] add_ln840_72_fu_1737_p2;
wire  signed [10:0] sext_ln840_102_fu_1743_p1;
wire  signed [10:0] sext_ln840_100_fu_1723_p1;
wire   [10:0] add_ln840_73_fu_1747_p2;
wire  signed [11:0] sext_ln840_103_fu_1753_p1;
wire  signed [11:0] sext_ln840_99_fu_1707_p1;
wire   [11:0] add_ln840_74_fu_1757_p2;
wire   [8:0] add_ln840_75_fu_1767_p2;
wire  signed [9:0] sext_ln840_106_fu_1777_p1;
wire  signed [9:0] sext_ln840_105_fu_1773_p1;
wire   [9:0] sub_ln840_28_fu_1781_p2;
wire  signed [10:0] sext_ln840_107_fu_1787_p1;
wire   [10:0] add_ln840_76_fu_1791_p2;
wire   [8:0] add_ln840_77_fu_1801_p2;
wire  signed [9:0] sext_ln840_109_fu_1807_p1;
wire   [9:0] add_ln840_78_fu_1811_p2;
wire   [8:0] add_ln840_79_fu_1821_p2;
wire  signed [9:0] sext_ln840_111_fu_1827_p1;
wire   [9:0] add_ln840_80_fu_1831_p2;
wire  signed [10:0] sext_ln840_112_fu_1837_p1;
wire  signed [10:0] sext_ln840_110_fu_1817_p1;
wire   [10:0] add_ln840_81_fu_1841_p2;
wire  signed [11:0] sext_ln840_113_fu_1847_p1;
wire  signed [11:0] sext_ln840_108_fu_1797_p1;
wire   [11:0] add_ln840_82_fu_1851_p2;
wire  signed [12:0] sext_ln840_114_fu_1857_p1;
wire  signed [12:0] sext_ln840_104_fu_1763_p1;
wire   [8:0] sub_ln840_2_fu_1867_p2;
wire   [8:0] ret_V_22_fu_1231_p2;
wire  signed [9:0] sext_ln840_116_fu_1877_p1;
wire   [9:0] sub_ln840_29_fu_1881_p2;
wire  signed [9:0] sext_ln840_115_fu_1873_p1;
wire   [9:0] add_ln840_84_fu_1887_p2;
wire  signed [9:0] sext_ln840_118_fu_1897_p1;
wire   [9:0] sub_ln840_30_fu_1901_p2;
wire   [9:0] add_ln840_85_fu_1907_p2;
wire  signed [10:0] sext_ln840_119_fu_1913_p1;
wire  signed [10:0] sext_ln840_117_fu_1893_p1;
wire   [10:0] add_ln840_86_fu_1917_p2;
wire   [9:0] sub_ln840_31_fu_1927_p2;
wire   [9:0] add_ln840_87_fu_1933_p2;
wire   [9:0] sub_ln840_32_fu_1943_p2;
wire   [9:0] add_ln840_88_fu_1949_p2;
wire  signed [10:0] sext_ln840_122_fu_1955_p1;
wire  signed [10:0] sext_ln840_121_fu_1939_p1;
wire   [10:0] add_ln840_89_fu_1959_p2;
wire  signed [11:0] sext_ln840_123_fu_1965_p1;
wire  signed [11:0] sext_ln840_120_fu_1923_p1;
wire   [11:0] add_ln840_90_fu_1969_p2;
wire   [9:0] sub_ln840_33_fu_1979_p2;
wire   [9:0] add_ln840_91_fu_1985_p2;
wire   [8:0] ret_V_16_fu_625_p2;
wire  signed [9:0] sext_ln840_127_fu_1999_p1;
wire  signed [9:0] sext_ln840_126_fu_1995_p1;
wire   [9:0] sub_ln840_34_fu_2003_p2;
wire   [9:0] add_ln840_92_fu_2009_p2;
wire  signed [10:0] sext_ln840_128_fu_2015_p1;
wire  signed [10:0] sext_ln840_125_fu_1991_p1;
wire   [10:0] add_ln840_93_fu_2019_p2;
wire   [8:0] ret_V_21_fu_1009_p2;
wire  signed [9:0] sext_ln840_130_fu_2029_p1;
wire   [9:0] sub_ln840_35_fu_2033_p2;
wire   [9:0] add_ln840_94_fu_2039_p2;
wire   [8:0] sub_ln840_36_fu_2049_p2;
wire  signed [9:0] sext_ln840_133_fu_2059_p1;
wire  signed [9:0] sext_ln840_132_fu_2055_p1;
wire   [9:0] sub_ln840_37_fu_2063_p2;
wire  signed [10:0] sext_ln840_134_fu_2069_p1;
wire  signed [10:0] sext_ln840_131_fu_2045_p1;
wire   [10:0] add_ln840_95_fu_2073_p2;
wire  signed [11:0] sext_ln840_135_fu_2079_p1;
wire  signed [11:0] sext_ln840_129_fu_2025_p1;
wire   [11:0] add_ln840_96_fu_2083_p2;
wire  signed [12:0] sext_ln840_136_fu_2089_p1;
wire  signed [12:0] sext_ln840_124_fu_1975_p1;
wire   [12:0] add_ln840_16_fu_953_p2;
wire   [12:0] add_ln840_33_fu_1225_p2;
wire   [12:0] add_ln840_49_fu_1441_p2;
wire   [12:0] add_ln840_68_fu_1679_p2;
wire   [12:0] add_ln840_83_fu_1861_p2;
wire   [12:0] add_ln840_97_fu_2093_p2;
wire   [5:0] p_Result_s_fu_2140_p7;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_start_int;
reg    ap_condition_1545;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & (ap_loop_exit_ready == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1545)) begin
        if ((icmp_ln123_fu_179_p2 == 1'd0)) begin
            i_fu_154 <= i_2_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_154 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln123_reg_2162 <= icmp_ln123_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln123_fu_179_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        result_V_1_reg_2171 <= result_V_1_fu_2105_p2;
        result_V_2_reg_2176 <= result_V_2_fu_2111_p2;
        result_V_3_reg_2181 <= result_V_3_fu_2117_p2;
        result_V_4_reg_2186 <= result_V_4_fu_2123_p2;
        result_V_5_reg_2191 <= result_V_5_fu_2129_p2;
        result_V_reg_2166 <= result_V_fu_2099_p2;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln123_fu_179_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_154;
    end
end

always @ (*) begin
    if (((icmp_ln123_fu_179_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln123_fu_179_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln123_reg_2162 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & (icmp_ln123_reg_2162 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out0_V_TVALID = 1'b1;
    end else begin
        out0_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else if (((~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & ~((ap_start_int == 1'b0) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0))) & (icmp_ln123_reg_2162_pp0_iter0_reg == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_893_p2 = ($signed(sext_ln840_1_fu_251_p1) + $signed(sext_ln840_2_fu_641_p1));

assign add_ln840_11_fu_903_p2 = ($signed(sext_ln840_25_fu_899_p1) + $signed(sext_ln628_2_fu_237_p1));

assign add_ln840_12_fu_913_p2 = ($signed(sext_ln840_4_fu_673_p1) + $signed(sext_ln840_5_fu_691_p1));

assign add_ln840_13_fu_923_p2 = ($signed(sext_ln840_27_fu_919_p1) + $signed(sext_ln628_17_fu_659_p1));

assign add_ln840_14_fu_933_p2 = ($signed(sext_ln840_28_fu_929_p1) + $signed(sext_ln840_26_fu_909_p1));

assign add_ln840_15_fu_943_p2 = ($signed(sext_ln840_29_fu_939_p1) + $signed(sext_ln840_24_fu_889_p1));

assign add_ln840_16_fu_953_p2 = ($signed(sext_ln840_30_fu_949_p1) + $signed(sext_ln840_18_fu_835_p1));

assign add_ln840_17_fu_979_p2 = ($signed(sub_ln840_1_fu_973_p2) + $signed(sext_ln840_31_fu_965_p1));

assign add_ln840_18_fu_1035_p2 = ($signed(sub_ln840_10_fu_1029_p2) + $signed(sext_ln628_4_fu_319_p1));

assign add_ln840_19_fu_1045_p2 = ($signed(sext_ln840_36_fu_1041_p1) + $signed(sub_ln840_9_fu_1023_p2));

assign add_ln840_1_fu_759_p2 = ($signed(sub_ln840_4_fu_753_p2) + $signed(sext_ln628_4_fu_319_p1));

assign add_ln840_20_fu_1065_p2 = ($signed(sub_ln840_11_fu_1059_p2) + $signed(sext_ln628_9_fu_439_p1));

assign add_ln840_21_fu_1085_p2 = ($signed(sub_ln840_12_fu_1079_p2) + $signed(sext_ln628_14_fu_559_p1));

assign add_ln840_22_fu_1095_p2 = ($signed(sext_ln840_41_fu_1091_p1) + $signed(sext_ln840_39_fu_1071_p1));

assign add_ln840_23_fu_1105_p2 = ($signed(sext_ln840_42_fu_1101_p1) + $signed(sext_ln840_37_fu_1051_p1));

assign add_ln840_24_fu_1135_p2 = ($signed(sext_ln1494_5_fu_357_p1) + $signed(sext_ln1494_6_fu_381_p1));

assign add_ln840_25_fu_1145_p2 = ($signed(sext_ln840_46_fu_1141_p1) + $signed(sext_ln840_7_fu_725_p1));

assign add_ln840_26_fu_1155_p2 = ($signed(sext_ln840_47_fu_1151_p1) + $signed(sext_ln840_45_fu_1131_p1));

assign add_ln840_27_fu_1165_p2 = ($signed(sext_ln1494_11_fu_501_p1) + $signed(sext_ln1494_15_fu_597_p1));

assign add_ln840_28_fu_1175_p2 = ($signed(sext_ln840_49_fu_1171_p1) + $signed(sext_ln840_15_fu_799_p1));

assign add_ln840_29_fu_1185_p2 = ($signed(sext_ln840_5_fu_691_p1) + $signed(sext_ln1494_17_fu_705_p1));

assign add_ln840_2_fu_769_p2 = ($signed(sext_ln840_11_fu_765_p1) + $signed(sext_ln840_9_fu_745_p1));

assign add_ln840_30_fu_1195_p2 = ($signed(sext_ln840_51_fu_1191_p1) + $signed(sext_ln840_21_fu_859_p1));

assign add_ln840_31_fu_1205_p2 = ($signed(sext_ln840_52_fu_1201_p1) + $signed(sext_ln840_50_fu_1181_p1));

assign add_ln840_32_fu_1215_p2 = ($signed(sext_ln840_53_fu_1211_p1) + $signed(sext_ln840_48_fu_1161_p1));

assign add_ln840_33_fu_1225_p2 = ($signed(sext_ln840_54_fu_1221_p1) + $signed(sext_ln840_43_fu_1111_p1));

assign add_ln840_34_fu_1261_p2 = ($signed(sub_ln840_16_fu_1255_p2) + $signed(sext_ln628_3_fu_275_p1));

assign add_ln840_35_fu_1271_p2 = ($signed(sext_ln840_58_fu_1267_p1) + $signed(sub_ln840_15_fu_1245_p2));

assign add_ln840_36_fu_1287_p2 = ($signed(sub_ln840_17_fu_1281_p2) + $signed(sext_ln628_5_fu_343_p1));

assign add_ln840_37_fu_1307_p2 = ($signed(sub_ln840_18_fu_1301_p2) + $signed(sext_ln628_8_fu_415_p1));

assign add_ln840_38_fu_1317_p2 = ($signed(sext_ln840_62_fu_1313_p1) + $signed(sext_ln840_60_fu_1293_p1));

assign add_ln840_39_fu_1327_p2 = ($signed(sext_ln840_63_fu_1323_p1) + $signed(sext_ln840_59_fu_1277_p1));

assign add_ln840_3_fu_789_p2 = ($signed(sub_ln840_5_fu_783_p2) + $signed(sext_ln628_7_fu_391_p1));

assign add_ln840_40_fu_1337_p2 = ($signed(sext_ln1494_9_fu_453_p1) + $signed(sext_ln1494_12_fu_525_p1));

assign add_ln840_41_fu_1361_p2 = ($signed(sext_ln1494_14_fu_573_p1) + $signed(sext_ln1494_15_fu_597_p1));

assign add_ln840_42_fu_1371_p2 = ($signed(sext_ln840_68_fu_1367_p1) + $signed(sext_ln840_19_fu_839_p1));

assign add_ln840_43_fu_1381_p2 = ($signed(sext_ln840_69_fu_1377_p1) + $signed(sext_ln840_67_fu_1357_p1));

assign add_ln840_44_fu_1391_p2 = ($signed(sext_ln840_2_fu_641_p1) + $signed(sext_ln840_3_fu_655_p1));

assign add_ln840_45_fu_1401_p2 = ($signed(sext_ln840_71_fu_1397_p1) + $signed(sext_ln840_21_fu_859_p1));

assign add_ln840_46_fu_1411_p2 = ($signed(sext_ln840_51_fu_1191_p1) + $signed(sext_ln628_18_fu_677_p1));

assign add_ln840_47_fu_1421_p2 = ($signed(sext_ln840_73_fu_1417_p1) + $signed(sext_ln840_72_fu_1407_p1));

assign add_ln840_48_fu_1431_p2 = ($signed(sext_ln840_74_fu_1427_p1) + $signed(sext_ln840_70_fu_1387_p1));

assign add_ln840_49_fu_1441_p2 = ($signed(sext_ln840_75_fu_1437_p1) + $signed(sext_ln840_64_fu_1333_p1));

assign add_ln840_4_fu_809_p2 = ($signed(sub_ln840_6_fu_803_p2) + $signed(sext_ln628_10_fu_463_p1));

assign add_ln840_50_fu_1447_p2 = ($signed(sext_ln628_1_fu_219_p1) + $signed(sext_ln1494_fu_195_p1));

assign add_ln840_51_fu_1473_p2 = ($signed(sub_ln840_20_fu_1467_p2) + $signed(sext_ln840_76_fu_1453_p1));

assign add_ln840_52_fu_1493_p2 = ($signed(sub_ln840_21_fu_1487_p2) + $signed(sext_ln628_6_fu_367_p1));

assign add_ln840_53_fu_1503_p2 = ($signed(sext_ln840_80_fu_1499_p1) + $signed(sext_ln840_78_fu_1479_p1));

assign add_ln840_54_fu_1519_p2 = ($signed(sub_ln840_22_fu_1513_p2) + $signed(sext_ln628_11_fu_487_p1));

assign add_ln840_55_fu_1549_p2 = ($signed(sext_ln840_84_fu_1545_p1) + $signed(sext_ln840_82_fu_1525_p1));

assign add_ln840_56_fu_1559_p2 = ($signed(sext_ln840_85_fu_1555_p1) + $signed(sext_ln840_81_fu_1509_p1));

assign add_ln840_57_fu_1569_p2 = ($signed(sext_ln1494_3_fu_309_p1) + $signed(sext_ln1494_4_fu_333_p1));

assign add_ln840_58_fu_1579_p2 = ($signed(sext_ln840_87_fu_1575_p1) + $signed(sext_ln840_57_fu_1251_p1));

assign add_ln840_59_fu_1589_p2 = ($signed(sext_ln1494_8_fu_429_p1) + $signed(sext_ln1494_11_fu_501_p1));

assign add_ln840_5_fu_819_p2 = ($signed(sext_ln840_16_fu_815_p1) + $signed(sext_ln840_14_fu_795_p1));

assign add_ln840_60_fu_1599_p2 = ($signed(sext_ln840_89_fu_1595_p1) + $signed(sext_ln840_13_fu_779_p1));

assign add_ln840_61_fu_1609_p2 = ($signed(sext_ln840_90_fu_1605_p1) + $signed(sext_ln840_88_fu_1585_p1));

assign add_ln840_62_fu_1619_p2 = ($signed(sext_ln1494_13_fu_549_p1) + $signed(sext_ln840_2_fu_641_p1));

assign add_ln840_63_fu_1629_p2 = ($signed(sext_ln840_92_fu_1625_p1) + $signed(sext_ln840_55_fu_1237_p1));

assign add_ln840_64_fu_1639_p2 = ($signed(sext_ln840_4_fu_673_p1) + $signed(sext_ln1494_17_fu_705_p1));

assign add_ln840_65_fu_1649_p2 = ($signed(sext_ln840_94_fu_1645_p1) + $signed(sext_ln628_17_fu_659_p1));

assign add_ln840_66_fu_1659_p2 = ($signed(sext_ln840_95_fu_1655_p1) + $signed(sext_ln840_93_fu_1635_p1));

assign add_ln840_67_fu_1669_p2 = ($signed(sext_ln840_96_fu_1665_p1) + $signed(sext_ln840_91_fu_1615_p1));

assign add_ln840_68_fu_1679_p2 = ($signed(sext_ln840_97_fu_1675_p1) + $signed(sext_ln840_86_fu_1565_p1));

assign add_ln840_69_fu_1691_p2 = ($signed(sub_ln840_25_fu_1685_p2) + $signed(sext_ln840_76_fu_1453_p1));

assign add_ln840_6_fu_829_p2 = ($signed(sext_ln840_17_fu_825_p1) + $signed(sext_ln840_12_fu_775_p1));

assign add_ln840_70_fu_1701_p2 = ($signed(sext_ln840_20_fu_855_p1) + $signed(sext_ln840_98_fu_1697_p1));

assign add_ln840_71_fu_1717_p2 = ($signed(sub_ln840_26_fu_1711_p2) + $signed(sext_ln628_16_fu_607_p1));

assign add_ln840_72_fu_1737_p2 = ($signed(sub_ln840_27_fu_1731_p2) + $signed(sext_ln1494_19_fu_1005_p1));

assign add_ln840_73_fu_1747_p2 = ($signed(sext_ln840_102_fu_1743_p1) + $signed(sext_ln840_100_fu_1723_p1));

assign add_ln840_74_fu_1757_p2 = ($signed(sext_ln840_103_fu_1753_p1) + $signed(sext_ln840_99_fu_1707_p1));

assign add_ln840_75_fu_1767_p2 = ($signed(sext_ln840_1_fu_251_p1) + $signed(sext_ln1494_1_fu_265_p1));

assign add_ln840_76_fu_1791_p2 = ($signed(sext_ln840_88_fu_1585_p1) + $signed(sext_ln840_107_fu_1787_p1));

assign add_ln840_77_fu_1801_p2 = ($signed(sext_ln1494_6_fu_381_p1) + $signed(sext_ln1494_7_fu_405_p1));

assign add_ln840_78_fu_1811_p2 = ($signed(sext_ln840_109_fu_1807_p1) + $signed(sext_ln840_33_fu_985_p1));

assign add_ln840_79_fu_1821_p2 = ($signed(sext_ln1494_10_fu_477_p1) + $signed(sext_ln1494_11_fu_501_p1));

assign add_ln840_7_fu_849_p2 = ($signed(sub_ln840_7_fu_843_p2) + $signed(sext_ln628_13_fu_535_p1));

assign add_ln840_80_fu_1831_p2 = ($signed(sext_ln840_111_fu_1827_p1) + $signed(sext_ln840_38_fu_1055_p1));

assign add_ln840_81_fu_1841_p2 = ($signed(sext_ln840_112_fu_1837_p1) + $signed(sext_ln840_110_fu_1817_p1));

assign add_ln840_82_fu_1851_p2 = ($signed(sext_ln840_113_fu_1847_p1) + $signed(sext_ln840_108_fu_1797_p1));

assign add_ln840_83_fu_1861_p2 = ($signed(sext_ln840_114_fu_1857_p1) + $signed(sext_ln840_104_fu_1763_p1));

assign add_ln840_84_fu_1887_p2 = ($signed(sub_ln840_29_fu_1881_p2) + $signed(sext_ln840_115_fu_1873_p1));

assign add_ln840_85_fu_1907_p2 = ($signed(sub_ln840_30_fu_1901_p2) + $signed(sext_ln628_3_fu_275_p1));

assign add_ln840_86_fu_1917_p2 = ($signed(sext_ln840_119_fu_1913_p1) + $signed(sext_ln840_117_fu_1893_p1));

assign add_ln840_87_fu_1933_p2 = ($signed(sub_ln840_31_fu_1927_p2) + $signed(sext_ln628_6_fu_367_p1));

assign add_ln840_88_fu_1949_p2 = ($signed(sub_ln840_32_fu_1943_p2) + $signed(sext_ln628_9_fu_439_p1));

assign add_ln840_89_fu_1959_p2 = ($signed(sext_ln840_122_fu_1955_p1) + $signed(sext_ln840_121_fu_1939_p1));

assign add_ln840_8_fu_873_p2 = ($signed(sub_ln840_8_fu_867_p2) + $signed(sext_ln628_16_fu_607_p1));

assign add_ln840_90_fu_1969_p2 = ($signed(sext_ln840_123_fu_1965_p1) + $signed(sext_ln840_120_fu_1923_p1));

assign add_ln840_91_fu_1985_p2 = ($signed(sub_ln840_33_fu_1979_p2) + $signed(sext_ln628_12_fu_511_p1));

assign add_ln840_92_fu_2009_p2 = ($signed(sub_ln840_34_fu_2003_p2) + $signed(sext_ln628_15_fu_583_p1));

assign add_ln840_93_fu_2019_p2 = ($signed(sext_ln840_128_fu_2015_p1) + $signed(sext_ln840_125_fu_1991_p1));

assign add_ln840_94_fu_2039_p2 = ($signed(sub_ln840_35_fu_2033_p2) + $signed(sext_ln1494_18_fu_995_p1));

assign add_ln840_95_fu_2073_p2 = ($signed(sext_ln840_134_fu_2069_p1) + $signed(sext_ln840_131_fu_2045_p1));

assign add_ln840_96_fu_2083_p2 = ($signed(sext_ln840_135_fu_2079_p1) + $signed(sext_ln840_129_fu_2025_p1));

assign add_ln840_97_fu_2093_p2 = ($signed(sext_ln840_136_fu_2089_p1) + $signed(sext_ln840_124_fu_1975_p1));

assign add_ln840_9_fu_883_p2 = ($signed(sext_ln840_23_fu_879_p1) + $signed(sext_ln840_20_fu_855_p1));

assign add_ln840_fu_739_p2 = ($signed(sub_ln840_3_fu_733_p2) + $signed(sext_ln840_6_fu_721_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1545 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln123_reg_2162 == 1'd0) & (out0_V_TREADY == 1'b0)))) | ((icmp_ln123_fu_179_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_2_fu_185_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign icmp_ln123_fu_179_p2 = ((ap_sig_allocacmp_i_1 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln123_reg_2162_pp0_iter0_reg = icmp_ln123_reg_2162;

assign out0_V_TDATA = p_Result_s_fu_2140_p7;

assign p_Result_s_fu_2140_p7 = {{{{{{result_V_5_reg_2191}, {result_V_4_reg_2186}}, {result_V_3_reg_2181}}, {result_V_2_reg_2176}}, {result_V_1_reg_2171}}, {result_V_reg_2166}};

assign r_V_10_fu_395_p4 = {{in0_V_TDATA[87:80]}};

assign r_V_11_fu_419_p4 = {{in0_V_TDATA[95:88]}};

assign r_V_12_fu_443_p4 = {{in0_V_TDATA[103:96]}};

assign r_V_13_fu_467_p4 = {{in0_V_TDATA[111:104]}};

assign r_V_14_fu_491_p4 = {{in0_V_TDATA[119:112]}};

assign r_V_15_fu_515_p4 = {{in0_V_TDATA[127:120]}};

assign r_V_16_fu_539_p4 = {{in0_V_TDATA[135:128]}};

assign r_V_17_fu_563_p4 = {{in0_V_TDATA[143:136]}};

assign r_V_18_fu_587_p4 = {{in0_V_TDATA[151:144]}};

assign r_V_19_fu_611_p4 = {{in0_V_TDATA[159:152]}};

assign r_V_1_fu_205_p4 = {{in0_V_TDATA[15:8]}};

assign r_V_20_fu_631_p4 = {{in0_V_TDATA[167:160]}};

assign r_V_21_fu_645_p4 = {{in0_V_TDATA[175:168]}};

assign r_V_22_fu_663_p4 = {{in0_V_TDATA[183:176]}};

assign r_V_23_fu_681_p4 = {{in0_V_TDATA[191:184]}};

assign r_V_24_fu_695_p4 = {{in0_V_TDATA[199:192]}};

assign r_V_2_fu_223_p4 = {{in0_V_TDATA[23:16]}};

assign r_V_3_fu_241_p4 = {{in0_V_TDATA[31:24]}};

assign r_V_4_fu_255_p4 = {{in0_V_TDATA[39:32]}};

assign r_V_5_fu_279_p4 = {{in0_V_TDATA[47:40]}};

assign r_V_6_fu_299_p4 = {{in0_V_TDATA[55:48]}};

assign r_V_7_fu_323_p4 = {{in0_V_TDATA[63:56]}};

assign r_V_8_fu_347_p4 = {{in0_V_TDATA[71:64]}};

assign r_V_9_fu_371_p4 = {{in0_V_TDATA[79:72]}};

assign r_V_fu_191_p1 = in0_V_TDATA[7:0];

assign result_V_1_fu_2105_p2 = (($signed(add_ln840_33_fu_1225_p2) > $signed(13'd1071)) ? 1'b1 : 1'b0);

assign result_V_2_fu_2111_p2 = (($signed(add_ln840_49_fu_1441_p2) > $signed(13'd106)) ? 1'b1 : 1'b0);

assign result_V_3_fu_2117_p2 = (($signed(add_ln840_68_fu_1679_p2) > $signed(13'd7448)) ? 1'b1 : 1'b0);

assign result_V_4_fu_2123_p2 = (($signed(add_ln840_83_fu_1861_p2) > $signed(13'd738)) ? 1'b1 : 1'b0);

assign result_V_5_fu_2129_p2 = (($signed(add_ln840_97_fu_2093_p2) > $signed(13'd2127)) ? 1'b1 : 1'b0);

assign result_V_fu_2099_p2 = (($signed(add_ln840_16_fu_953_p2) > $signed(13'd8075)) ? 1'b1 : 1'b0);

assign ret_V_10_fu_481_p2 = ($signed(9'd0) - $signed(sext_ln1494_10_fu_477_p1));

assign ret_V_11_fu_505_p2 = ($signed(9'd0) - $signed(sext_ln1494_11_fu_501_p1));

assign ret_V_12_fu_529_p2 = ($signed(9'd0) - $signed(sext_ln1494_12_fu_525_p1));

assign ret_V_13_fu_553_p2 = ($signed(9'd0) - $signed(sext_ln1494_13_fu_549_p1));

assign ret_V_14_fu_577_p2 = ($signed(9'd0) - $signed(sext_ln1494_14_fu_573_p1));

assign ret_V_15_fu_601_p2 = ($signed(9'd0) - $signed(sext_ln1494_15_fu_597_p1));

assign ret_V_16_fu_625_p2 = ($signed(9'd0) - $signed(sext_ln1494_16_fu_621_p1));

assign ret_V_17_fu_709_p2 = ($signed(9'd0) - $signed(sext_ln1494_17_fu_705_p1));

assign ret_V_18_fu_959_p2 = ($signed(9'd0) - $signed(sext_ln840_fu_233_p1));

assign ret_V_19_fu_989_p2 = ($signed(9'd0) - $signed(sext_ln840_2_fu_641_p1));

assign ret_V_1_fu_269_p2 = ($signed(9'd0) - $signed(sext_ln1494_1_fu_265_p1));

assign ret_V_20_fu_999_p2 = ($signed(9'd0) - $signed(sext_ln840_3_fu_655_p1));

assign ret_V_21_fu_1009_p2 = ($signed(9'd0) - $signed(sext_ln840_4_fu_673_p1));

assign ret_V_22_fu_1231_p2 = ($signed(9'd0) - $signed(sext_ln840_1_fu_251_p1));

assign ret_V_23_fu_1457_p2 = ($signed(9'd0) - $signed(sext_ln840_5_fu_691_p1));

assign ret_V_2_fu_293_p2 = ($signed(9'd0) - $signed(sext_ln1494_2_fu_289_p1));

assign ret_V_3_fu_313_p2 = ($signed(9'd0) - $signed(sext_ln1494_3_fu_309_p1));

assign ret_V_4_fu_337_p2 = ($signed(9'd0) - $signed(sext_ln1494_4_fu_333_p1));

assign ret_V_5_fu_361_p2 = ($signed(9'd0) - $signed(sext_ln1494_5_fu_357_p1));

assign ret_V_6_fu_385_p2 = ($signed(9'd0) - $signed(sext_ln1494_6_fu_381_p1));

assign ret_V_7_fu_409_p2 = ($signed(9'd0) - $signed(sext_ln1494_7_fu_405_p1));

assign ret_V_8_fu_433_p2 = ($signed(9'd0) - $signed(sext_ln1494_8_fu_429_p1));

assign ret_V_9_fu_457_p2 = ($signed(9'd0) - $signed(sext_ln1494_9_fu_453_p1));

assign ret_V_fu_199_p2 = ($signed(9'd0) - $signed(sext_ln1494_fu_195_p1));

assign sext_ln1494_10_fu_477_p1 = r_V_13_fu_467_p4;

assign sext_ln1494_11_fu_501_p1 = r_V_14_fu_491_p4;

assign sext_ln1494_12_fu_525_p1 = r_V_15_fu_515_p4;

assign sext_ln1494_13_fu_549_p1 = r_V_16_fu_539_p4;

assign sext_ln1494_14_fu_573_p1 = r_V_17_fu_563_p4;

assign sext_ln1494_15_fu_597_p1 = r_V_18_fu_587_p4;

assign sext_ln1494_16_fu_621_p1 = r_V_19_fu_611_p4;

assign sext_ln1494_17_fu_705_p1 = r_V_24_fu_695_p4;

assign sext_ln1494_18_fu_995_p1 = $signed(ret_V_19_fu_989_p2);

assign sext_ln1494_19_fu_1005_p1 = $signed(ret_V_20_fu_999_p2);

assign sext_ln1494_1_fu_265_p1 = r_V_4_fu_255_p4;

assign sext_ln1494_2_fu_289_p1 = r_V_5_fu_279_p4;

assign sext_ln1494_3_fu_309_p1 = r_V_6_fu_299_p4;

assign sext_ln1494_4_fu_333_p1 = r_V_7_fu_323_p4;

assign sext_ln1494_5_fu_357_p1 = r_V_8_fu_347_p4;

assign sext_ln1494_6_fu_381_p1 = r_V_9_fu_371_p4;

assign sext_ln1494_7_fu_405_p1 = r_V_10_fu_395_p4;

assign sext_ln1494_8_fu_429_p1 = r_V_11_fu_419_p4;

assign sext_ln1494_9_fu_453_p1 = r_V_12_fu_443_p4;

assign sext_ln1494_fu_195_p1 = $signed(r_V_fu_191_p1);

assign sext_ln628_10_fu_463_p1 = $signed(ret_V_9_fu_457_p2);

assign sext_ln628_11_fu_487_p1 = $signed(ret_V_10_fu_481_p2);

assign sext_ln628_12_fu_511_p1 = $signed(ret_V_11_fu_505_p2);

assign sext_ln628_13_fu_535_p1 = $signed(ret_V_12_fu_529_p2);

assign sext_ln628_14_fu_559_p1 = $signed(ret_V_13_fu_553_p2);

assign sext_ln628_15_fu_583_p1 = $signed(ret_V_14_fu_577_p2);

assign sext_ln628_16_fu_607_p1 = $signed(ret_V_15_fu_601_p2);

assign sext_ln628_17_fu_659_p1 = r_V_21_fu_645_p4;

assign sext_ln628_18_fu_677_p1 = r_V_22_fu_663_p4;

assign sext_ln628_1_fu_219_p1 = r_V_1_fu_205_p4;

assign sext_ln628_2_fu_237_p1 = r_V_2_fu_223_p4;

assign sext_ln628_3_fu_275_p1 = $signed(ret_V_1_fu_269_p2);

assign sext_ln628_4_fu_319_p1 = $signed(ret_V_3_fu_313_p2);

assign sext_ln628_5_fu_343_p1 = $signed(ret_V_4_fu_337_p2);

assign sext_ln628_6_fu_367_p1 = $signed(ret_V_5_fu_361_p2);

assign sext_ln628_7_fu_391_p1 = $signed(ret_V_6_fu_385_p2);

assign sext_ln628_8_fu_415_p1 = $signed(ret_V_7_fu_409_p2);

assign sext_ln628_9_fu_439_p1 = $signed(ret_V_8_fu_433_p2);

assign sext_ln628_fu_215_p1 = r_V_1_fu_205_p4;

assign sext_ln840_100_fu_1723_p1 = $signed(add_ln840_71_fu_1717_p2);

assign sext_ln840_101_fu_1727_p1 = $signed(ret_V_23_fu_1457_p2);

assign sext_ln840_102_fu_1743_p1 = $signed(add_ln840_72_fu_1737_p2);

assign sext_ln840_103_fu_1753_p1 = $signed(add_ln840_73_fu_1747_p2);

assign sext_ln840_104_fu_1763_p1 = $signed(add_ln840_74_fu_1757_p2);

assign sext_ln840_105_fu_1773_p1 = r_V_24_fu_695_p4;

assign sext_ln840_106_fu_1777_p1 = $signed(add_ln840_75_fu_1767_p2);

assign sext_ln840_107_fu_1787_p1 = $signed(sub_ln840_28_fu_1781_p2);

assign sext_ln840_108_fu_1797_p1 = $signed(add_ln840_76_fu_1791_p2);

assign sext_ln840_109_fu_1807_p1 = $signed(add_ln840_77_fu_1801_p2);

assign sext_ln840_10_fu_749_p1 = r_V_7_fu_323_p4;

assign sext_ln840_110_fu_1817_p1 = $signed(add_ln840_78_fu_1811_p2);

assign sext_ln840_111_fu_1827_p1 = $signed(add_ln840_79_fu_1821_p2);

assign sext_ln840_112_fu_1837_p1 = $signed(add_ln840_80_fu_1831_p2);

assign sext_ln840_113_fu_1847_p1 = $signed(add_ln840_81_fu_1841_p2);

assign sext_ln840_114_fu_1857_p1 = $signed(add_ln840_82_fu_1851_p2);

assign sext_ln840_115_fu_1873_p1 = $signed(sub_ln840_2_fu_1867_p2);

assign sext_ln840_116_fu_1877_p1 = $signed(ret_V_22_fu_1231_p2);

assign sext_ln840_117_fu_1893_p1 = $signed(add_ln840_84_fu_1887_p2);

assign sext_ln840_118_fu_1897_p1 = r_V_6_fu_299_p4;

assign sext_ln840_119_fu_1913_p1 = $signed(add_ln840_85_fu_1907_p2);

assign sext_ln840_11_fu_765_p1 = $signed(add_ln840_1_fu_759_p2);

assign sext_ln840_120_fu_1923_p1 = $signed(add_ln840_86_fu_1917_p2);

assign sext_ln840_121_fu_1939_p1 = $signed(add_ln840_87_fu_1933_p2);

assign sext_ln840_122_fu_1955_p1 = $signed(add_ln840_88_fu_1949_p2);

assign sext_ln840_123_fu_1965_p1 = $signed(add_ln840_89_fu_1959_p2);

assign sext_ln840_124_fu_1975_p1 = $signed(add_ln840_90_fu_1969_p2);

assign sext_ln840_125_fu_1991_p1 = $signed(add_ln840_91_fu_1985_p2);

assign sext_ln840_126_fu_1995_p1 = r_V_18_fu_587_p4;

assign sext_ln840_127_fu_1999_p1 = $signed(ret_V_16_fu_625_p2);

assign sext_ln840_128_fu_2015_p1 = $signed(add_ln840_92_fu_2009_p2);

assign sext_ln840_129_fu_2025_p1 = $signed(add_ln840_93_fu_2019_p2);

assign sext_ln840_12_fu_775_p1 = $signed(add_ln840_2_fu_769_p2);

assign sext_ln840_130_fu_2029_p1 = $signed(ret_V_21_fu_1009_p2);

assign sext_ln840_131_fu_2045_p1 = $signed(add_ln840_94_fu_2039_p2);

assign sext_ln840_132_fu_2055_p1 = r_V_23_fu_681_p4;

assign sext_ln840_133_fu_2059_p1 = $signed(sub_ln840_36_fu_2049_p2);

assign sext_ln840_134_fu_2069_p1 = $signed(sub_ln840_37_fu_2063_p2);

assign sext_ln840_135_fu_2079_p1 = $signed(add_ln840_95_fu_2073_p2);

assign sext_ln840_136_fu_2089_p1 = $signed(add_ln840_96_fu_2083_p2);

assign sext_ln840_13_fu_779_p1 = r_V_10_fu_395_p4;

assign sext_ln840_14_fu_795_p1 = $signed(add_ln840_3_fu_789_p2);

assign sext_ln840_15_fu_799_p1 = r_V_13_fu_467_p4;

assign sext_ln840_16_fu_815_p1 = $signed(add_ln840_4_fu_809_p2);

assign sext_ln840_17_fu_825_p1 = $signed(add_ln840_5_fu_819_p2);

assign sext_ln840_18_fu_835_p1 = $signed(add_ln840_6_fu_829_p2);

assign sext_ln840_19_fu_839_p1 = r_V_16_fu_539_p4;

assign sext_ln840_1_fu_251_p1 = r_V_3_fu_241_p4;

assign sext_ln840_20_fu_855_p1 = $signed(add_ln840_7_fu_849_p2);

assign sext_ln840_21_fu_859_p1 = r_V_19_fu_611_p4;

assign sext_ln840_22_fu_863_p1 = $signed(ret_V_17_fu_709_p2);

assign sext_ln840_23_fu_879_p1 = $signed(add_ln840_8_fu_873_p2);

assign sext_ln840_24_fu_889_p1 = $signed(add_ln840_9_fu_883_p2);

assign sext_ln840_25_fu_899_p1 = $signed(add_ln840_10_fu_893_p2);

assign sext_ln840_26_fu_909_p1 = $signed(add_ln840_11_fu_903_p2);

assign sext_ln840_27_fu_919_p1 = $signed(add_ln840_12_fu_913_p2);

assign sext_ln840_28_fu_929_p1 = $signed(add_ln840_13_fu_923_p2);

assign sext_ln840_29_fu_939_p1 = $signed(add_ln840_14_fu_933_p2);

assign sext_ln840_2_fu_641_p1 = $signed(r_V_20_fu_631_p4);

assign sext_ln840_30_fu_949_p1 = $signed(add_ln840_15_fu_943_p2);

assign sext_ln840_31_fu_965_p1 = $signed(ret_V_18_fu_959_p2);

assign sext_ln840_32_fu_969_p1 = $signed(ret_V_fu_199_p2);

assign sext_ln840_33_fu_985_p1 = r_V_8_fu_347_p4;

assign sext_ln840_34_fu_1015_p1 = r_V_5_fu_279_p4;

assign sext_ln840_35_fu_1019_p1 = $signed(add_ln840_17_fu_979_p2);

assign sext_ln840_36_fu_1041_p1 = $signed(add_ln840_18_fu_1035_p2);

assign sext_ln840_37_fu_1051_p1 = $signed(add_ln840_19_fu_1045_p2);

assign sext_ln840_38_fu_1055_p1 = r_V_12_fu_443_p4;

assign sext_ln840_39_fu_1071_p1 = $signed(add_ln840_20_fu_1065_p2);

assign sext_ln840_3_fu_655_p1 = r_V_21_fu_645_p4;

assign sext_ln840_40_fu_1075_p1 = r_V_17_fu_563_p4;

assign sext_ln840_41_fu_1091_p1 = $signed(add_ln840_21_fu_1085_p2);

assign sext_ln840_42_fu_1101_p1 = $signed(add_ln840_22_fu_1095_p2);

assign sext_ln840_43_fu_1111_p1 = $signed(add_ln840_23_fu_1105_p2);

assign sext_ln840_44_fu_1121_p1 = $signed(sub_ln840_13_fu_1115_p2);

assign sext_ln840_45_fu_1131_p1 = $signed(sub_ln840_14_fu_1125_p2);

assign sext_ln840_46_fu_1141_p1 = $signed(add_ln840_24_fu_1135_p2);

assign sext_ln840_47_fu_1151_p1 = $signed(add_ln840_25_fu_1145_p2);

assign sext_ln840_48_fu_1161_p1 = $signed(add_ln840_26_fu_1155_p2);

assign sext_ln840_49_fu_1171_p1 = $signed(add_ln840_27_fu_1165_p2);

assign sext_ln840_4_fu_673_p1 = r_V_22_fu_663_p4;

assign sext_ln840_50_fu_1181_p1 = $signed(add_ln840_28_fu_1175_p2);

assign sext_ln840_51_fu_1191_p1 = $signed(add_ln840_29_fu_1185_p2);

assign sext_ln840_52_fu_1201_p1 = $signed(add_ln840_30_fu_1195_p2);

assign sext_ln840_53_fu_1211_p1 = $signed(add_ln840_31_fu_1205_p2);

assign sext_ln840_54_fu_1221_p1 = $signed(add_ln840_32_fu_1215_p2);

assign sext_ln840_55_fu_1237_p1 = r_V_15_fu_515_p4;

assign sext_ln840_56_fu_1241_p1 = r_V_3_fu_241_p4;

assign sext_ln840_57_fu_1251_p1 = r_V_5_fu_279_p4;

assign sext_ln840_58_fu_1267_p1 = $signed(add_ln840_34_fu_1261_p2);

assign sext_ln840_59_fu_1277_p1 = $signed(add_ln840_35_fu_1271_p2);

assign sext_ln840_5_fu_691_p1 = r_V_23_fu_681_p4;

assign sext_ln840_60_fu_1293_p1 = $signed(add_ln840_36_fu_1287_p2);

assign sext_ln840_61_fu_1297_p1 = r_V_11_fu_419_p4;

assign sext_ln840_62_fu_1313_p1 = $signed(add_ln840_37_fu_1307_p2);

assign sext_ln840_63_fu_1323_p1 = $signed(add_ln840_38_fu_1317_p2);

assign sext_ln840_64_fu_1333_p1 = $signed(add_ln840_39_fu_1327_p2);

assign sext_ln840_65_fu_1343_p1 = r_V_14_fu_491_p4;

assign sext_ln840_66_fu_1347_p1 = $signed(add_ln840_40_fu_1337_p2);

assign sext_ln840_67_fu_1357_p1 = $signed(sub_ln840_19_fu_1351_p2);

assign sext_ln840_68_fu_1367_p1 = $signed(add_ln840_41_fu_1361_p2);

assign sext_ln840_69_fu_1377_p1 = $signed(add_ln840_42_fu_1371_p2);

assign sext_ln840_6_fu_721_p1 = $signed(sub_ln840_fu_715_p2);

assign sext_ln840_70_fu_1387_p1 = $signed(add_ln840_43_fu_1381_p2);

assign sext_ln840_71_fu_1397_p1 = $signed(add_ln840_44_fu_1391_p2);

assign sext_ln840_72_fu_1407_p1 = $signed(add_ln840_45_fu_1401_p2);

assign sext_ln840_73_fu_1417_p1 = $signed(add_ln840_46_fu_1411_p2);

assign sext_ln840_74_fu_1427_p1 = $signed(add_ln840_47_fu_1421_p2);

assign sext_ln840_75_fu_1437_p1 = $signed(add_ln840_48_fu_1431_p2);

assign sext_ln840_76_fu_1453_p1 = $signed(add_ln840_50_fu_1447_p2);

assign sext_ln840_77_fu_1463_p1 = r_V_3_fu_241_p4;

assign sext_ln840_78_fu_1479_p1 = $signed(add_ln840_51_fu_1473_p2);

assign sext_ln840_79_fu_1483_p1 = r_V_9_fu_371_p4;

assign sext_ln840_7_fu_725_p1 = r_V_4_fu_255_p4;

assign sext_ln840_80_fu_1499_p1 = $signed(add_ln840_52_fu_1493_p2);

assign sext_ln840_81_fu_1509_p1 = $signed(add_ln840_53_fu_1503_p2);

assign sext_ln840_82_fu_1525_p1 = $signed(add_ln840_54_fu_1519_p2);

assign sext_ln840_83_fu_1535_p1 = $signed(sub_ln840_23_fu_1529_p2);

assign sext_ln840_84_fu_1545_p1 = $signed(sub_ln840_24_fu_1539_p2);

assign sext_ln840_85_fu_1555_p1 = $signed(add_ln840_55_fu_1549_p2);

assign sext_ln840_86_fu_1565_p1 = $signed(add_ln840_56_fu_1559_p2);

assign sext_ln840_87_fu_1575_p1 = $signed(add_ln840_57_fu_1569_p2);

assign sext_ln840_88_fu_1585_p1 = $signed(add_ln840_58_fu_1579_p2);

assign sext_ln840_89_fu_1595_p1 = $signed(add_ln840_59_fu_1589_p2);

assign sext_ln840_8_fu_729_p1 = $signed(ret_V_2_fu_293_p2);

assign sext_ln840_90_fu_1605_p1 = $signed(add_ln840_60_fu_1599_p2);

assign sext_ln840_91_fu_1615_p1 = $signed(add_ln840_61_fu_1609_p2);

assign sext_ln840_92_fu_1625_p1 = $signed(add_ln840_62_fu_1619_p2);

assign sext_ln840_93_fu_1635_p1 = $signed(add_ln840_63_fu_1629_p2);

assign sext_ln840_94_fu_1645_p1 = $signed(add_ln840_64_fu_1639_p2);

assign sext_ln840_95_fu_1655_p1 = $signed(add_ln840_65_fu_1649_p2);

assign sext_ln840_96_fu_1665_p1 = $signed(add_ln840_66_fu_1659_p2);

assign sext_ln840_97_fu_1675_p1 = $signed(add_ln840_67_fu_1669_p2);

assign sext_ln840_98_fu_1697_p1 = $signed(add_ln840_69_fu_1691_p2);

assign sext_ln840_99_fu_1707_p1 = $signed(add_ln840_70_fu_1701_p2);

assign sext_ln840_9_fu_745_p1 = $signed(add_ln840_fu_739_p2);

assign sext_ln840_fu_233_p1 = r_V_2_fu_223_p4;

assign sub_ln840_10_fu_1029_p2 = ($signed(sext_ln628_8_fu_415_p1) - $signed(sext_ln840_10_fu_749_p1));

assign sub_ln840_11_fu_1059_p2 = ($signed(sext_ln628_13_fu_535_p1) - $signed(sext_ln840_38_fu_1055_p1));

assign sub_ln840_12_fu_1079_p2 = ($signed(sext_ln1494_18_fu_995_p1) - $signed(sext_ln840_40_fu_1075_p1));

assign sub_ln840_13_fu_1115_p2 = ($signed(sext_ln840_1_fu_251_p1) - $signed(sext_ln840_4_fu_673_p1));

assign sub_ln840_14_fu_1125_p2 = ($signed(sext_ln840_44_fu_1121_p1) - $signed(sext_ln628_17_fu_659_p1));

assign sub_ln840_15_fu_1245_p2 = ($signed(sext_ln840_35_fu_1019_p1) - $signed(sext_ln840_56_fu_1241_p1));

assign sub_ln840_16_fu_1255_p2 = ($signed(sext_ln628_4_fu_319_p1) - $signed(sext_ln840_57_fu_1251_p1));

assign sub_ln840_17_fu_1281_p2 = ($signed(sext_ln628_7_fu_391_p1) - $signed(sext_ln840_33_fu_985_p1));

assign sub_ln840_18_fu_1301_p2 = ($signed(sext_ln628_11_fu_487_p1) - $signed(sext_ln840_61_fu_1297_p1));

assign sub_ln840_19_fu_1351_p2 = ($signed(sext_ln840_66_fu_1347_p1) - $signed(sext_ln840_65_fu_1343_p1));

assign sub_ln840_1_fu_973_p2 = ($signed(sext_ln840_32_fu_969_p1) - $signed(sext_ln628_fu_215_p1));

assign sub_ln840_20_fu_1467_p2 = ($signed(sext_ln628_3_fu_275_p1) - $signed(sext_ln840_77_fu_1463_p1));

assign sub_ln840_21_fu_1487_p2 = ($signed(sext_ln628_10_fu_463_p1) - $signed(sext_ln840_79_fu_1483_p1));

assign sub_ln840_22_fu_1513_p2 = ($signed(sext_ln628_16_fu_607_p1) - $signed(sext_ln840_40_fu_1075_p1));

assign sub_ln840_23_fu_1529_p2 = ($signed(sext_ln840_fu_233_p1) - $signed(sext_ln840_5_fu_691_p1));

assign sub_ln840_24_fu_1539_p2 = ($signed(sext_ln840_83_fu_1535_p1) - $signed(sext_ln840_21_fu_859_p1));

assign sub_ln840_25_fu_1685_p2 = ($signed(sext_ln628_9_fu_439_p1) - $signed(sext_ln628_2_fu_237_p1));

assign sub_ln840_26_fu_1711_p2 = ($signed(sext_ln1494_18_fu_995_p1) - $signed(sext_ln840_21_fu_859_p1));

assign sub_ln840_27_fu_1731_p2 = ($signed(sext_ln840_101_fu_1727_p1) - $signed(sext_ln628_18_fu_677_p1));

assign sub_ln840_28_fu_1781_p2 = ($signed(sext_ln840_106_fu_1777_p1) - $signed(sext_ln840_105_fu_1773_p1));

assign sub_ln840_29_fu_1881_p2 = ($signed(sext_ln840_116_fu_1877_p1) - $signed(sext_ln628_2_fu_237_p1));

assign sub_ln840_2_fu_1867_p2 = ($signed(sext_ln1494_fu_195_p1) - $signed(sext_ln628_1_fu_219_p1));

assign sub_ln840_30_fu_1901_p2 = ($signed(sext_ln628_5_fu_343_p1) - $signed(sext_ln840_118_fu_1897_p1));

assign sub_ln840_31_fu_1927_p2 = ($signed(sext_ln628_8_fu_415_p1) - $signed(sext_ln840_79_fu_1483_p1));

assign sub_ln840_32_fu_1943_p2 = ($signed(sext_ln628_11_fu_487_p1) - $signed(sext_ln840_38_fu_1055_p1));

assign sub_ln840_33_fu_1979_p2 = ($signed(sext_ln628_14_fu_559_p1) - $signed(sext_ln840_55_fu_1237_p1));

assign sub_ln840_34_fu_2003_p2 = ($signed(sext_ln840_127_fu_1999_p1) - $signed(sext_ln840_126_fu_1995_p1));

assign sub_ln840_35_fu_2033_p2 = ($signed(sext_ln840_130_fu_2029_p1) - $signed(sext_ln628_17_fu_659_p1));

assign sub_ln840_36_fu_2049_p2 = ($signed(sext_ln1494_2_fu_289_p1) - $signed(sext_ln1494_17_fu_705_p1));

assign sub_ln840_37_fu_2063_p2 = ($signed(sext_ln840_133_fu_2059_p1) - $signed(sext_ln840_132_fu_2055_p1));

assign sub_ln840_3_fu_733_p2 = ($signed(sext_ln840_8_fu_729_p1) - $signed(sext_ln840_7_fu_725_p1));

assign sub_ln840_4_fu_753_p2 = ($signed(sext_ln628_6_fu_367_p1) - $signed(sext_ln840_10_fu_749_p1));

assign sub_ln840_5_fu_783_p2 = ($signed(sext_ln628_9_fu_439_p1) - $signed(sext_ln840_13_fu_779_p1));

assign sub_ln840_6_fu_803_p2 = ($signed(sext_ln628_12_fu_511_p1) - $signed(sext_ln840_15_fu_799_p1));

assign sub_ln840_7_fu_843_p2 = ($signed(sext_ln628_15_fu_583_p1) - $signed(sext_ln840_19_fu_839_p1));

assign sub_ln840_8_fu_867_p2 = ($signed(sext_ln840_22_fu_863_p1) - $signed(sext_ln840_21_fu_859_p1));

assign sub_ln840_9_fu_1023_p2 = ($signed(sext_ln840_35_fu_1019_p1) - $signed(sext_ln840_34_fu_1015_p1));

assign sub_ln840_fu_715_p2 = ($signed(sext_ln628_1_fu_219_p1) - $signed(sext_ln1494_fu_195_p1));

endmodule //MVAU_hls_0_Matrix_Vector_Activate_Batch
