-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingMaxPool_hls_0_StreamingMaxPool_hls_0_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in0_V_TVALID : IN STD_LOGIC;
    in0_V_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in0_V_TREADY : OUT STD_LOGIC;
    buf_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_we0 : OUT STD_LOGIC;
    buf_V_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf_V_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_ce1 : OUT STD_LOGIC;
    buf_V_q1 : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of StreamingMaxPool_hls_0_StreamingMaxPool_hls_0_Pipeline_VITIS_LOOP_79_3_VITIS_LOOP_80_4_VITIS_LOOP_82_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal icmp_ln79_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in0_V_TDATA_blk_n : STD_LOGIC;
    signal icmp_ln79_reg_326 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_326_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_326_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_330 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln79_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln79_reg_335 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_192_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_reg_340 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_reg_340_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln82_1_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_1_reg_345 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_1_reg_345_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_1_reg_345_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal buf_V_addr_reg_349 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln80_fu_275_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_fu_58 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_lhs_V_load : STD_LOGIC_VECTOR (5 downto 0);
    signal kx_fu_62 : STD_LOGIC_VECTOR (1 downto 0);
    signal kx_1_fu_204_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_kx_load : STD_LOGIC_VECTOR (1 downto 0);
    signal xp_fu_66 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln80_1_fu_268_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln80_2_fu_224_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten14_fu_74 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln79_fu_138_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten14_load : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln82_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln79_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rhs_V_fu_188_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln80_fu_180_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln82_fu_198_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln80_1_fu_218_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln79_fu_255_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln80_fu_262_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_280 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component StreamingMaxPool_hls_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component StreamingMaxPool_hls_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif ((ap_const_logic_1 = ap_CS_iter1_fsm_state2)) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    indvar_flatten14_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln79_fu_132_p2 = ap_const_lv1_0)) then 
                    indvar_flatten14_fu_74 <= add_ln79_fu_138_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten14_fu_74 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln79_fu_132_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_70 <= select_ln80_2_fu_224_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_70 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    kx_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln79_fu_132_p2 = ap_const_lv1_0)) then 
                    kx_fu_62 <= kx_1_fu_204_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_62 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_V_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln79_fu_132_p2 = ap_const_lv1_0)) then 
                    lhs_V_fu_58 <= ret_V_fu_192_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    lhs_V_fu_58 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    xp_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                xp_fu_66 <= ap_const_lv4_0;
            elsif (((icmp_ln79_reg_326_pp0_iter0_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                xp_fu_66 <= select_ln80_1_fu_268_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                and_ln79_reg_335 <= and_ln79_fu_168_p2;
                icmp_ln80_reg_330 <= icmp_ln80_fu_150_p2;
                icmp_ln82_1_reg_345 <= icmp_ln82_1_fu_212_p2;
                ret_V_reg_340 <= ret_V_fu_192_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln79_reg_326 <= icmp_ln79_fu_132_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln79_reg_326_pp0_iter0_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (icmp_ln82_1_reg_345_pp0_iter0_reg = ap_const_lv1_1))) then
                buf_V_addr_reg_349 <= zext_ln80_fu_275_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_iter1_fsm_state2)) then
                icmp_ln79_reg_326_pp0_iter1_reg <= icmp_ln79_reg_326;
                icmp_ln82_1_reg_345_pp0_iter1_reg <= icmp_ln82_1_reg_345;
                ret_V_reg_340_pp0_iter1_reg <= ret_V_reg_340;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, ap_CS_iter1_fsm_state2, ap_CS_iter2_fsm_state3, icmp_ln79_reg_326_pp0_iter1_reg)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((ap_const_logic_0 = ap_CS_iter1_fsm_state2)) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                elsif (((ap_const_logic_1 = ap_CS_iter1_fsm_state2) or ((icmp_ln79_reg_326_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((ap_const_logic_1 = ap_CS_iter1_fsm_state2)) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    add_ln79_fu_138_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten14_load) + unsigned(ap_const_lv6_1));
    add_ln80_1_fu_218_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv6_1));
    add_ln80_fu_262_p2 <= std_logic_vector(unsigned(select_ln79_fu_255_p3) + unsigned(ap_const_lv4_1));
    add_ln82_fu_198_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_kx_load) + unsigned(ap_const_lv2_1));
    and_ln79_fu_168_p2 <= (xor_ln79_fu_156_p2 and icmp_ln82_fu_162_p2);
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_280_assign_proc : process(ap_CS_iter0_fsm_state1, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
                ap_condition_280 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_iter0_fsm_state1, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln79_fu_132_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_iter2_fsm_state3, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_iter0_fsm_state1, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten14_load_assign_proc : process(ap_CS_iter0_fsm_state1, ap_loop_init, indvar_flatten14_fu_74)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten14_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten14_load <= indvar_flatten14_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_iter0_fsm_state1, ap_loop_init, indvar_flatten_fu_70)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_kx_load_assign_proc : process(ap_CS_iter0_fsm_state1, ap_loop_init, kx_fu_62)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_kx_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kx_load <= kx_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_lhs_V_load_assign_proc : process(ap_CS_iter0_fsm_state1, lhs_V_fu_58, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_lhs_V_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_lhs_V_load <= lhs_V_fu_58;
        end if; 
    end process;

    buf_V_address0 <= buf_V_addr_reg_349;
    buf_V_address1 <= zext_ln80_fu_275_p1(4 - 1 downto 0);

    buf_V_ce0_assign_proc : process(ap_CS_iter2_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_iter2_fsm_state3)) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(ap_CS_iter1_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_iter1_fsm_state2)) then 
            buf_V_ce1 <= ap_const_logic_1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_d0 <= (ret_V_reg_340_pp0_iter1_reg or buf_V_q1);

    buf_V_we0_assign_proc : process(ap_CS_iter2_fsm_state3, icmp_ln79_reg_326_pp0_iter1_reg, icmp_ln82_1_reg_345_pp0_iter1_reg)
    begin
        if (((icmp_ln79_reg_326_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (icmp_ln82_1_reg_345_pp0_iter1_reg = ap_const_lv1_1))) then 
            buf_V_we0 <= ap_const_logic_1;
        else 
            buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln79_fu_132_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten14_load = ap_const_lv6_38) else "0";
    icmp_ln79_reg_326_pp0_iter0_reg <= icmp_ln79_reg_326;
    icmp_ln80_fu_150_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv6_1C) else "0";
    icmp_ln82_1_fu_212_p2 <= "1" when (kx_1_fu_204_p3 = ap_const_lv2_2) else "0";
    icmp_ln82_1_reg_345_pp0_iter0_reg <= icmp_ln82_1_reg_345;
    icmp_ln82_fu_162_p2 <= "1" when (ap_sig_allocacmp_kx_load = ap_const_lv2_2) else "0";

    in0_V_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        if (((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            in0_V_TDATA_blk_n <= in0_V_TVALID;
        else 
            in0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in0_V_TREADY_assign_proc : process(ap_CS_iter0_fsm_state1, in0_V_TVALID, icmp_ln79_fu_132_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln79_fu_132_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            in0_V_TREADY <= ap_const_logic_1;
        else 
            in0_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    kx_1_fu_204_p3 <= 
        ap_const_lv2_1 when (or_ln80_fu_174_p2(0) = '1') else 
        add_ln82_fu_198_p2;
    or_ln80_fu_174_p2 <= (icmp_ln80_fu_150_p2 or and_ln79_fu_168_p2);
    ret_V_fu_192_p2 <= (select_ln80_fu_180_p3 or rhs_V_fu_188_p1);
    rhs_V_fu_188_p1 <= in0_V_TDATA(6 - 1 downto 0);
    select_ln79_fu_255_p3 <= 
        ap_const_lv4_0 when (icmp_ln80_reg_330(0) = '1') else 
        xp_fu_66;
    select_ln80_1_fu_268_p3 <= 
        add_ln80_fu_262_p2 when (and_ln79_reg_335(0) = '1') else 
        select_ln79_fu_255_p3;
    select_ln80_2_fu_224_p3 <= 
        ap_const_lv6_1 when (icmp_ln80_fu_150_p2(0) = '1') else 
        add_ln80_1_fu_218_p2;
    select_ln80_fu_180_p3 <= 
        ap_const_lv6_0 when (or_ln80_fu_174_p2(0) = '1') else 
        ap_sig_allocacmp_lhs_V_load;
    xor_ln79_fu_156_p2 <= (icmp_ln80_fu_150_p2 xor ap_const_lv1_1);
    zext_ln80_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln80_1_fu_268_p3),64));
end behav;
